# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System - > Seismic Records Event Save Seismic signals MSEED and SAC Format

# Andalusian Institute of Geophysics
# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Granada University, (Ugr), Spain, 2021 - 2023

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 7 - Convert_1.py -> Save events from a MSEED and SAC format

# Part of the comments are written, both in English and in Castilian (Spanish).


# Load libraries to use

# For system use, threads and paths (path)
import sys
import os
import subprocess
from pathlib import Path

import warnings  # librería para alertas

# Libraries for graphics using matplotlib and using numpy, plotly
import numpy as np
from numpy import arange, array
from matplotlib import pyplot
from matplotlib.widgets import SpanSelector, MultiCursor

# Libraries for the use of PyQt5 - binding of the graphical Qt library
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtWidgets import *
import sys

from PyQt5 import QtGui

# Identify the operating system
import platform
sistema = platform.system()  # Identify the operating system

# Libraries to use tkinter (Graphical interface)
import tkinter
import tkinter as tk
from tkinter.ttk import Combobox, Style
from tkinter.messagebox import showerror, showinfo, askyesno
from tkinter import Frame, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT

# En caso de utilizar la ventana como root (cambios a posteriori)
from tkinter import *
root = tk.Tk()
root.withdraw()

from os.path import join as os_path_join
from os.path import dirname as os_path_dirname

# import matplotlib.cbook as cbook
import numpy as np
from numpy import arange, array
from matplotlib import pyplot
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector, MultiCursor

# To read records through the "obspy" library
import obspy
from obspy.imaging.cm import obspy_sequential
from obspy.signal.tf_misfit import cwt
from obspy import Stream
from obspy import read
from obspy.io.sac import SACTrace
from obspy import read, Trace

from obspy.core import UTCDateTime, Stream, Trace, read, AttribDict
from obspy.core.util import NamedTemporaryFile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 413)
        icon = QtGui.QIcon()

        # Loading the Ugr image on the canvas
        icon.addPixmap(QtGui.QPixmap(r"Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 100, 701, 201))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")


        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(190, 30, 501, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_4.setPalette(palette)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(190, 10, 181, 16))
        self.label_5.setObjectName("label_5")

        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(10, 90, 691, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(190, 120, 171, 16))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(190, 140, 501, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.line_9 = QtWidgets.QFrame(self.frame_2)
        self.line_9.setGeometry(QtCore.QRect(170, 0, 16, 201))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 130, 101, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/save_dir.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")


        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 101, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Load.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")

        self.line_13 = QtWidgets.QFrame(self.frame_2)
        self.line_13.setGeometry(QtCore.QRect(0, 0, 16, 201))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(310, 80, 211, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 320, 701, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(800, 0, 16, 61))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(450, 20, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/save_file.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 20, 101, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/Back.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(590, 20, 101, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon4)
        self.pushButton_7.setObjectName("pushButton_7")

        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(250, 0, 181, 61))
        self.label_10.setObjectName("label_10")

        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 81, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(140, 0, 20, 71))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_8 = QtWidgets.QFrame(self.frame_3)
        self.line_8.setGeometry(QtCore.QRect(420, 0, 20, 71))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.line_11 = QtWidgets.QFrame(self.frame_3)
        self.line_11.setGeometry(QtCore.QRect(560, 0, 20, 71))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 10, 91, 81))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/Ugr.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 50, 101, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/Clean.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 411, 31))
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Command Buttons
        self.pushButton.setStyleSheet("background-color: bisque; color: blue")              # Text and Color of the Command Button (load File)
        self.pushButton_2.setStyleSheet("background-color: honeydew; color: blue")          # Text and Color of the Command Button (clean input)
        self.pushButton_3.setStyleSheet("background-color: silver; color: blue")            # Text and Color of the Command Button (Save Dir)
        self.pushButton_5.setStyleSheet("background-color: burlywood; color: blue")         # Text and Color of the Command Button (Safe File MSEED or SAC Format)
        self.pushButton_6.setStyleSheet("background-color: CornflowerBlue; color: white")   # Text and Color of the Command Button (Go Back)
        self.pushButton_7.setStyleSheet("background-color: gold; color: blue")              # Text and Color of the Command Button (Exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Save Seismic Signals - University of Granada (Ugr)"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#142cc8;\">Seismic Record Path to Upload</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#142cc8;\">Seismic Record Path to Save</span></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Save directory"))
        self.pushButton_3.setText(_translate("MainWindow", " Save Dir"))
        self.pushButton.setToolTip(_translate("MainWindow", "Load Record"))
        self.pushButton.setText(_translate("MainWindow", " Load"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#aa0000;\">Load files and paths - save records:</span></p></body></html>"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Save File"))
        self.pushButton_5.setText(_translate("MainWindow", " Save File"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "Exit System"))
        self.pushButton_7.setText(_translate("MainWindow", " Exit"))
        self.label_10.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Warning</span><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">: </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-style:italic;\">Make sure that the record to upload</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-style:italic;\">and folder to storage are selected.</span></p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "Go Back"))
        self.pushButton_6.setText(_translate("MainWindow", " Go Back"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Clean Inputs"))
        self.pushButton_2.setText(_translate("MainWindow", " Clean Inputs"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#5555ff;\">Save Records in MSEED or SAC Format</span></p></body></html>"))

        # Command button actions, function calls
        self.pushButton.clicked.connect(self.abrir_archivo2)            # Call the function to upload file (Load File).
        self.pushButton_2.clicked.connect(self.limpiar_entradas)        # Calls the function to clean entries (Clean Entries).
        self.pushButton_3.clicked.connect(self.guardar)                 # Calls the function to save Dir (Save Dir).
        self.pushButton_5.clicked.connect(self.verificar2)              # Call the function to save records (MSEED or SAC).
        self.pushButton_6.clicked.connect(self.abrir_programa1)         # Call the function to return to the Home Screen (Go Back).
        self.pushButton_7.clicked.connect(self.Exit1)                   # Call the function to exit the System (Exit System).

    def abrir_archivo2(self):                           # Function, to search and load the records according to the format

            if sistema == "Windows":                    # Si el sistema operativo es Windows
                self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta = Path(self.archivo_abierto)
                self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_4.setFont(font)                                      # Printing using text format.
                self.label_4.setText(self.archivo_abierto)                      # Printing on the file path label.

            else:                                       # En caso de que el sistema operativo sea diferente a Windows (Linux, Mac)
                self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta = Path(self.archivo_abierto)
                self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_4.setFont(font)                                      # Printing using text format.
                self.label_4.setText(self.archivo_abierto)                      # Printing on the file path label.

    def limpiar_entradas(self):                         # Dejar todo como al inicio


        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Clean all inputs.")
        msg.setText("Are you sure to delete all entries?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                    # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                       # If the answer is OK

            # Limpiar entradas Etiquetas y cajas de texto

            self.label_4.setText("")                        # Borra contenido etiqueta de Ruta de Archivo
            self.label_7.setText("")                        # Borra contenido etiqueta de Ruta de Guardar Archivo

        else:
            pass

    def guardar(self):                                                      # Función para búsqueda de registro de acuerdo al formato

        if sistema == "Windows":                                            # Si el sistema operativo es Windows
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_7.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_7.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

        else:                                                               # If the system is Linux or Mac
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()
            # Si se desea conocer la extensión del fichero : print("La extensión del Registro es: ", self.ruta4.suffix)

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_7.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_7.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

    """ Function to go back at home """

    def abrir_programa1(self):                                              # Call function to another program (Back)

        if sistema == "Windows":                                            # If the system is Windows
            plt.close()                                                     # Close the existing chart.
            subprocess.Popen(["python", "Menu.py"])
            app.quit()
        else:                                                               # If the system is Linux
            plt.close()                                                     # Close the existing chart
            subprocess.Popen(["python3", "Menu.py"])
            app.quit()


    """  Fuction to exit system  """

    def Exit1(self):                                                        # Call function to show exit dialog box

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Exit System")
        msg.setText("Are you sure to exit the System?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                   # If the answer is OK
            app.closeAllWindows()                                           # Close all windows


    """ Función de ventana de dialogo, la cual es llamada por el botón de salvar fichero MSEED o SAC """

    def verificar2(self):

            try:
                # Verificar que las entradas de etiquetas implicadas no estén vacías o entradas invalidas

                if not self.label_4.text():
                    MensCombo6 = QMessageBox()
                    MensCombo6.setIcon(QMessageBox.Warning)
                    MensCombo6.setWindowTitle("Path and file name Empty")
                    MensCombo6.setText("Please, enter a valid Value")
                    returnValue = MensCombo6.exec()

                elif not self.label_7.text():
                    MensCombo7 = QMessageBox()
                    MensCombo7.setIcon(QMessageBox.Warning)
                    MensCombo7.setWindowTitle("Path and Directory name Empty")
                    MensCombo7.setText("Please, enter a valid Value")
                    returnValue = MensCombo7.exec()

                else:

                    archivoFil1 = (self.label_4.text())                         # Lectura etiqueta del Record
                    archivoFil2 = (self.label_7.text())                         # Lectura etiqueta del Directorio

                    head, tail = os.path.split(self.archivo_abierto)

                    root, extension = os.path.splitext(tail)

                    st  = obspy.read(archivoFil1)                               # Lectura archivo de acuerdo al formato

                    tr = st[0]                     # Asigna el número de traza (por defecto 0) indicado al Stream para tratamiento del registro

                    # Ventana de dialogo (MessageBox) para guardar el corte por formatos SAC y MSEED
                    dialog = QMessageBox()
                    dialog.setWindowTitle("Save the event cut Record")
                    dialog.setText("Do you want to save MSEED or SAC Format?, CANCEL = Close all Windows")
                    # Se agregan los botones de comandos y se personalizan
                    dialog.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel | QMessageBox.No)
                    dialog.button(QMessageBox.Ok).setText("MSEED")
                    dialog.button(QMessageBox.Cancel).setText("CANCEL")
                    dialog.button(QMessageBox.No).setText("SAC")
                    # Se establece el tipo de icono a presentar
                    dialog.setIcon(QMessageBox.Question)

                    # Se ejecuta el dialog y se captura el resultado
                    returnValue = dialog.exec_()
                    # Ciclo en el que se comprueba que boton de comando ha sido ejecutado
                    if returnValue == QMessageBox.Ok:       # En caso de que la selección sea grabar con formato MSEED
                        F1 = (root + extension + '.MSEED')
                        F2 = (archivoFil2 + F1)
                        st[0].write( filename= (F2), format="MSEED")

                        showinfo(title = "File MSEED successfully created", message = "Successfully created record.\n\n")
                        plt.close()

                    elif returnValue == QMessageBox.No:     # En caso de que la selección sea grabar con formato SAC
                        F3 = (root + extension + '.SAC')
                        F4 = (archivoFil2 + F3)
                        st[0].write( filename= (F4), format="SAC")
                        showinfo(title = "File SAC successfully created", message = "Successfully created record.\n\n")
                        plt.close()

                    else:                                   # En caso de que la selñeccion sea cancelar
                        showinfo(title = "Close all Windows", message = "The windows close.\n\n")
                        plt.close()

            except:                                         # Validacion de cualquier posibilidad de error, presenta una ventana de dialogo
                plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setWindowTitle("Save the event cut Record")
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")
                msgBox.setWindowTitle("Invalid Record File")
                returnValue = msgBox.exec()
                pass



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
