# -*- coding: utf-8 -*-

# Created by: Tkinter UI code generator.
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System / One-day and continued day Records Charts module

# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Andalusian Institute of Geophysics.
# Granada University, (Ugr), Spain, 2021 - 2023

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 3: Days_1.py -> System for plotting 24-hour seismic records in one-hour segments and on one continuous plot

# Interface, for plot One-day and continued day Records Charts

# Load libraries to use

import os, warnings
import tkinter
from tkinter import *
import tkinter as tk
from tkinter import PhotoImage, messagebox
from PIL import Image,ImageTk
from tkinter import ttk
import matplotlib
import matplotlib.pyplot as plt

# Cargar y ver el sistema operativo que se maneja
import platform
sistema = platform.system()

# Para uso del sistema, subprocesos y rutas (path)
import sys
import subprocess                                               # One-day and continued day Records Charts
from pathlib import Path

import matplotlib.pyplot as plt

from tkinter import Frame, font, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT

root = tk.Tk()
root.geometry('832x385')
root.title("One-day and continued day Seismic Records Charts - University of Granada (UGR)")

# False implica que la imagen gif se aplica sólo a esta ventana del inicio y no a las futuras toplevels que se van a crear.
root.iconphoto(False, tk.PhotoImage(file='Images/Ugr.gif'))

from obspy import read
import obspy

# Cargar y ver el sistema operativo que se maneja
import platform
sistema = platform.system()

# Para prewsentar los tooltip text
from idlelib.tooltip import Hovertip

# Para impedir que la ventana sea redimensionable
root.resizable(width=False, height=False)

# *** ---- A partir de aqui se crean los objetos y las funciones ----- ****

# Para crear los Frame (canvas)
# frame1 -  Lienzo en la parte superior de la pantalla
# Hijo de root (padre)
frame1 = Frame(root)
# Empaqueta el frame en la raíz mediante la función "pack()"
frame1.pack()

# frame3 - Lienzo en la parte inferior de la pantalla
# Hijo de root (padre)
frame3 = Frame(root)
# Empaqueta el frame en la raíz mediante la función "pack()"
frame3.pack()

# Se establece la configuración  de los Frame *****

frame1.config(width=811,height=141)     # Se estable el tamaño que tendrá el frame (ancho x alto)
#frame1.pack(fill='both', expand=1)
frame1.pack(fill="x")                   # Se determina el ancho del frame que ubicará en el valor "x" horizontal igual al padre (root)
frame1.config(relief="raised")          # Se determina el tipo de relieve del frame: "hundido", Se pueden así mismo realizar las siguientes configuraciones:
# raised = Borde saliente, permite que el elemento que encierra parezca que se encuentra por encima del nivel de la superficie de la pantalla.
# sunken = borde hundido, permite que el elemento que encierra parezca que se encuentra por debajo del nivel de la superficie de la pantalla.
# groove = Borde hundido, que visualmente parece que se encuentra por debajo del nivel de la superficie de la pantalla
# ridge = Borde saliente, que visualmente parece que se encuentra por encima del nivel de la superficie de la pantalla
# flat = No se muestra ningún borde
frame1.config(bd=5)                     # Se establece el tamaño del borde en píxeles
frame1.place(x=10,y=10)                 # Ubicación en la pantalla del frame
# Color de fondo, background
frame1.config(bg="#d8e1f0")             # color de fondo del frame


frame3.config(width=811,height=81)      # Se estable el tamaño que tendrá el frma (ancho x alto)
#frame1.pack(fill='both', expand=1)
frame3.pack(fill="x")                   # Se determina el ancho del frame que ubicará en el valor "x" horizontal igual al padre (root)
frame3.config(relief="raised")          # Se determina el tipo de relieve del frame: "hundido"
frame3.config(bd=5)                     # tSe establece el tamaño del borde en píxeles
frame3.place(x=10,y=300)                # Ubicación en la pantalla del frame
# Color de fondo, background
frame3.config(bg="#fffedb")             # color de fondo del frame

# Se establecen las variables globales, para ello han de iniciarlar a valores nulos o ceros

etiqueta3 = " "            # Variable global para la etiqueta que contiene el path del registro
MinMagnitude = 0           # Variable global iniciada para la magnitud mínima
D1 = 0
F1 = 0                     # Variable global iniciada para filtro Paso-Bajo - Frecuencia
F2 = 0                     # Variable global iniciada para filtro Paso-Alto - Frecuencia
F3 = 0                     # Variable global iniciada para filtro Paso-Banda - Frecuencia Mínima
F4 = 0                     # Variable global iniciada para filtro Paso-Banda - Frecuencia Maxima
F1a = 0                    # Variable global iniciada para Filtro Paso-Bajo - Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)
F1b = 0                    # Variable global iniciada para Filtro Paso-Alto - Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)
F1c = 0                    # Variable global iniciada para Filtro Paso-Banda - Conversión del valor string de la caja de texto Frecuencia Mínima a valor flotante (decimales)
F1d = 0                    # Variable global iniciada para Filtro Paso-Banda - Conversión del valor string de la caja de texto Frecuencia Maxima a valor flotante (decimales)


# Crear la caja de texto para la entrada de la magnitud mínima a detectar.
caja1 = ttk.Entry()
caja1 = ttk.Entry(font=font.Font(family="Times", size=12), width=8, justify=tk.CENTER)
# Posicionarla en la ventana.
caja1.place(x=600, y=75)

# Crear la caja de texto para la entrada de la Frecuencia para los filtros Lowpass y Highpass
caja2 = ttk.Entry()
caja2 = ttk.Entry(font=font.Font(family="Times", size=10), width=5, justify=tk.CENTER)
# Posicionarla en la ventana.
caja2.place(x=15, y=272)

# Crear la caja de texto para la entrada de la Frecuencia Mínima para el filtro Bandhpass
caja3 = ttk.Entry()
caja3 = ttk.Entry(font=font.Font(family="Times", size=10), width=5, justify=tk.CENTER)
# Posicionarla en la ventana.
caja3.place(x=65, y=272)

# Crear la caja de texto para la entrada de la Frecuencia Maxima para el filtro Bandhpass
caja4 = ttk.Entry()
caja4 = ttk.Entry(font=font.Font(family="Times", size=10), width=5, justify=tk.CENTER)
# Posicionarla en la ventana.
caja4.place(x=115, y=272)


def temp_text(e):       # Función para eliminar el contenido de la caja de texto (opcional a utilizar)
   caja1.delete(0,"end")

# Se establece un Valor por defecto inicial para la caja1: Magnitud
caja1.insert(0, "6.5")

# Se desactiva la caja de texto Magnitud al inicio
caja1.config(state=tk.DISABLED)

# Se desactiva la caja de texto Frecuencia Mínima al inicio
caja3.config(state=tk.DISABLED)

# Se desactiva la caja de texto Frecuencia Maxima al inicio
caja4.config(state=tk.DISABLED)

# *** Se crean las imagenes que contendrán los iconos para las etiquetas ******

# Para la imagen del Botón 1
img = Image.open('Images/Load.gif')
#img = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img = ImageTk.PhotoImage(img)

# Para la imagen del Botón 2
img1 = Image.open('Images/Plot.gif')
#img1 = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img1 = ImageTk.PhotoImage(img1)

# Para la imagen del Botón 3
img4 = Image.open('Images/Plot2.gif')
#img1 = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img4 = ImageTk.PhotoImage(img4)

# Para la imagen del Botón 4
img5 = Image.open('Images/Clean.gif')
#img1 = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img5 = ImageTk.PhotoImage(img5)

# Para la imagen del Botón 5
img6 = Image.open('Images/Back.gif')
#img1 = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img6 = ImageTk.PhotoImage(img6)

# Para la imagen del Botón 6
img7 = Image.open('Images/Exit.gif')
#img7 = img.resize((20, 20), Image.ANTIALIAS) # Redimension (Alto, Ancho)
img7 = ImageTk.PhotoImage(img7)


# *** Para la etiqueta del logo de la Ugr ***
imagen=tk.PhotoImage(file="Images/UGR6.png")
#Aumenta las dimensiones de la imagen en un (2 * ancho_imagen)
#imagen_zoom=imagen.zoom(2)
#Reduce las dimensiones de la imagen en un (ancho_imagen / 2)
imagen_sub=imagen.subsample(2)

# *** --- Se crean las etiquetas (label), con los textos y colores de fono y de texto --- ****

etiqueta1=ttk.Label(image=imagen,background="#d8e1f0")
etiqueta1.place(x=161, y=21)

etiqueta2 = tk.Label(root, text="Initial and Final Values by UTC Date and Time", font=("Times", 12, "bold"), bg="#d8e1f0", fg="#aa1608")
etiqueta2.place(x=300,y=21)

etiqueta3 = tk.Label(root,text ="", font=("Times", 8), bg="#d8e1f0",fg="blue")
etiqueta3.place(x=120, y=324, width=585, height=43)

etiqueta4 = tk.Label(root, text="Record Path to Load : ", font=("Times", 10, "bold"),  bg="#fffedb", fg="#0000ff")  #
etiqueta4.place(x=160,y=303)

etiqueta5 = tk.Label(root, text="Select Filter", font=("Times", 9, "bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta5.place(x=45,y=123)

etiqueta6 = tk.Label(root, text="Path and Return / Exit Commands", font=("Times", 12, "bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta6.place(x=500,y=273)

etiqueta7 = tk.Label(root, text="Minimum Magnitude", font=("Times", 12, "bold"), bg="#d8e1f0", fg="#0000ff")
etiqueta7.place(x=450,y=75)

etiqueta8 = tk.Label(root, text="Charts plot commands", font=("Times", 12, "bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta8.place(x=555,y=153)

etiqueta9 = tk.Label(root, text="By default = 6.5", font=("Times", 8, "italic","bold"), bg="#d8e1f0", fg="#aa1608")
etiqueta9.place(x=593,y=102)

etiqueta10 = tk.Label(root, text="Frequency", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#aa1608")
etiqueta10.place(x=10,y=258)

etiqueta11 = tk.Label(root, text="Freq. Min.", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#aa1608")
etiqueta11.place(x=60,y=258)

etiqueta12 = tk.Label(root, text="Freq. Max.", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#aa1608")
etiqueta12.place(x=112,y=258)

etiqueta13 = tk.Label(root, text="By default, filter order = 4", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta13.place(x=30,y=153)

etiqueta14 = tk.Label(root, text="Magnitude is not needed", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta14.place(x=650,y=240)

etiqueta15 = tk.Label(root, text="Magnitude is needed", font=("Times", 7,"bold"), bg="#f0f0f0", fg="#0000ff")
etiqueta15.place(x=506,y=240)

# --- A partor de aquí se establecen las funciones a utilizar en el programa ---
# *** Se establecen las funciones ***

def cargar():                           # Función para búsqueda de registro de acuerdo al formato
        if sistema == "Windows":        # Si el sistema es Windows

            caja1.config(state=tk.NORMAL)               # Se activa la caja de texto Magnitud
            archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('NPY Files','*.npy'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('Kinemetrics Files','*.evt')))

            ruta = Path(archivo_abierto)
            ruta2 = ruta.joinpath(ruta).resolve()

            # Impresión en la eiqueta de la ruta del fichero
            global etiqueta3
            etiqueta3.config(text = archivo_abierto)

            head, tail = os.path.split(archivo_abierto)
            root, extension = os.path.splitext(tail)

        else:                                            # Si el Sistema es Linux
            caja1.config(state=tk.NORMAL)                # Se activa la caja de texto
            archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('NPY Files','*.npy'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('Kinemetrics Files','*.evt')))

            self.ruta = Path(archivo_abierto)
            self.ruta2 = ruta.joinpath(ruta).resolve()

            # Impresión en la eiqueta de la ruta del fichero
            etiqueta3.config(text = archivo_abierto)

            LG = etiqueta3.config(text = archivo_abierto)

            head, tail = os.path.split(archivo_abierto)
            root, extension = os.path.splitext(tail)


def grafica24_FiltroPB():          # Función para la gráfica de las 24 horas, 1 grafica por cada hora con filtro Paso-Bajo

    try:

        global D1               # Variable global y captura de valor de la caja de Texto de Magnitud
        D1 = caja1.get()

        global F1               # Variable global y captura de valor de la caja de Texto de Frecuencia para los filtros Paso-Bajo y Paso-Alto
        F1 = caja2.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0

        elif D1 == "":                          # Validación que la caja de texto de Magnitud no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Minimum Magnitude emply", message="Please, enter a valid Value")
            pass    # continue

        elif F1 == "":                          # Validación que la caja de texto de Frecuencia del filtro no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                D2 = float(D1)                  # Conversión del valor string de la caja de texto Magnitud a valor flotante (decimales)
                F1a = float(F1)                 # Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)

                if D2 >= 10:
                    # show the message
                    tkinter.messagebox.showerror(title="Minimum Magnitude is >= 10", message="Please, enter a valid Value < 10")
                    pass    # continue here
                else:

                    archivoFil1 =etiqueta3.cget("text")

                    st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                    head, tail = os.path.split(archivoFil1)
                    root, extension = os.path.splitext(archivoFil1)
                    root, extension = os.path.splitext(tail)

                    st.filter("lowpass", freq=F1a, corners=4, zerophase=True)        # Filtro paso-bajo - (orden 4 por defecto)

                    st.plot(type="dayplot", draw = True, interval = 60, right_vertical_labels=True,
                        vertical_scaling_range=5e3, one_tick_per_line=True,                             # linewidth=0.5  tamaño de las lineas
                        color=['k', 'r', 'b', 'g'], show_y_UTC_label=True,
                        x_labels_size=8, y_labels_size=8,
                        #tick_format = '%I :%M:%S %p',          # Si se desea cambiar el formato para AM/PM descomentarioar y utilizar esta linea
                        events={'min_magnitude': D2},                                                   # por defecto a 6.5 magnitud
                        title= "Lowpass Filter - Record : %s " % tail, title_size=14);

    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0

def grafica24_FiltroPA():          # Función para la gráfica de las 24 horas, 1 grafica por cada hora con filtro Paso-Alto

    try:

        global D1               # Variable global y captura de valor de la caja de Texto de Magnitud
        D1 = caja1.get()

        global F2               # Variable global y captura de valor de la caja de Texto de Frecuencia para los filtros Paso-Bajo y Paso-Alto
        F2 = caja2.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0

        elif D1 == "":                          # Validación que la caja de texto de Magnitud no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Minimum Magnitude emply", message="Please, enter a valid Value")
            pass    # continue

        elif F2 == "":                          # Validación que la caja de texto de Frecuencia del filtro no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                D2 = float(D1)                  # Conversión del valor string de la caja de texto Magnitud a valor flotante (decimales)
                F1b = float(F2)                 # Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)

                if D2 >= 10:
                    # show the message
                    tkinter.messagebox.showerror(title="Minimum Magnitude is >= 10", message="Please, enter a valid Value < 10")
                    pass    # continue here
                else:

                    archivoFil1 =etiqueta3.cget("text")

                    st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                    head, tail = os.path.split(archivoFil1)
                    root, extension = os.path.splitext(archivoFil1)
                    root, extension = os.path.splitext(tail)

                    st.filter("highpass", freq=F1b, corners=4, zerophase=True)        # Filtro paso-alto - (orden 4 por defecto)

                    st.plot(type="dayplot", draw = True, interval = 60, right_vertical_labels=True,
                        vertical_scaling_range=5e3, one_tick_per_line=True,                             # linewidth=0.5  tamaño de las lineas
                        color=['k', 'r', 'b', 'g'], show_y_UTC_label=True,
                        x_labels_size=8, y_labels_size=8,
                        #tick_format = '%I :%M:%S %p',          # Si se desea cambiar el formato para AM/PM descomentarioar y utilizar esta linea
                        events={'min_magnitude': D2},                                                   # por defecto a 6.5 magnitud
                        title= "Highpass Filter - RecordRecord : %s " % tail, title_size=14);

    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0

def grafica24_FiltroPD():       # Función para la gráfica de las 24 horas, 1 grafica por cada hora con filtro Paso-Banda

    try:

        global D1               # Variable global y captura de valor de la caja de Texto de Magnitud
        D1 = caja1.get()

        global F3               # Variable global y captura de valor de la caja de Texto de Frecuencia Mínima para el filtro Paso-Banda
        F3 = caja3.get()

        global F4               # Variable global y captura de valor de la caja de Texto de Frecuencia Maxima para el filtro Paso-Banda
        F4 = caja4.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0

        elif D1 == "":                          # Validación que la caja de texto de Magnitud no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Minimum Magnitude emply", message="Please, enter a valid Value")
            pass    # continue

        elif F3 == "":                          # Validación que la caja de texto de Frecuencia Mínima del filtro Paso-Banda no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Minimum Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        elif F4 == "":                          # Validación que la caja de texto de Frecuencia Maxima del filtro Paso-Banda no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Maximum Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                D2 = float(D1)                  # Conversión del valor string de la caja de texto Magnitud a valor flotante (decimales)
                F1c = float(F3)                 # Conversión del valor string de la caja de texto Frecuencia Mínima a valor flotante (decimales)
                F1d = float(F4)                 # Conversión del valor string de la caja de texto Frecuencia Maxima a valor flotante (decimales)

                if D2 >= 10:
                    # show the message
                    tkinter.messagebox.showerror(title="Minimum Magnitude is >= 10", message="Please, enter a valid Value < 10")
                    pass    # continue here
                else:

                    archivoFil1 =etiqueta3.cget("text")

                    st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                    head, tail = os.path.split(archivoFil1)
                    root, extension = os.path.splitext(archivoFil1)
                    root, extension = os.path.splitext(tail)

                    st.filter('bandpass', freqmin=F1c, freqmax=F1d, corners=4, zerophase=True)  # Filtro paso Banda de orden 4

                    st.plot(type="dayplot", draw = True, interval = 60, right_vertical_labels=True,
                        vertical_scaling_range=5e3, one_tick_per_line=True,                             # linewidth=0.5  tamaño de las lineas
                        color=['k', 'r', 'b', 'g'], show_y_UTC_label=True,
                        x_labels_size=8, y_labels_size=8,
                        #tick_format = '%I :%M:%S %p',          # Si se desea cambiar el formato para AM/PM descomentarioar y utilizar esta linea
                        events={'min_magnitude': D2},                                                   # por defecto a 6.5 magnitud
                        title= "Bandpass Filter - Record : %s " % tail, title_size=14);

    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0

# *** ---- Funciones para las Gráficas Continuas de acuerdo al filtro --- ***

def grafica_FiltroPB():          # Función para la gráfica continua con filtro Paso-Bajo

    try:

        global F1               # Variable global y captura de valor de la caja de Texto de Frecuencia para los filtros Paso-Bajo y Paso-Alto
        F1 = caja2.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0

        elif F1 == "":                          # Validación que la caja de texto de Frecuencia del filtro no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                F1a = float(F1)                 # Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)

                archivoFil1 =etiqueta3.cget("text")

                st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                head, tail = os.path.split(archivoFil1)
                root, extension = os.path.splitext(archivoFil1)
                root, extension = os.path.splitext(tail)

                st.filter("lowpass", freq=F1a, corners=4, zerophase=True)        # Filtro paso-bajo - (orden 4 por defecto)

                st.plot(color='blue')

    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0


def grafica_FiltroPA():          # Función para la gráfica continua con filtro Paso-Alto

    try:

        global F2               # Variable global y captura de valor de la caja de Texto de Frecuencia para los filtros Paso-Bajo y Paso-Alto
        F2 = caja2.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0

        elif F2 == "":                          # Validación que la caja de texto de Frecuencia del filtro no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                F1b = float(F2)                 # Conversión del valor string de la caja de texto Frecuencia a valor flotante (decimales)

                archivoFil1 =etiqueta3.cget("text")

                st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                head, tail = os.path.split(archivoFil1)
                root, extension = os.path.splitext(archivoFil1)
                root, extension = os.path.splitext(tail)

                st.filter("highpass", freq=F1b, corners=4, zerophase=True)        # Filtro paso-alto - (orden 4 por defecto)
                st.plot(color='blue')


    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0

def grafica_FiltroPD():         # Función para la gráfica continua con filtro Paso-Banda

    try:


        global F3               # Variable global y captura de valor de la caja de Texto de Frecuencia Mínima para el filtro Paso-Banda
        F3 = caja3.get()

        global F4               # Variable global y captura de valor de la caja de Texto de Frecuencia Maxima para el filtro Paso-Banda
        F4 = caja4.get()

        if etiqueta3.cget("text") == "":        # Validación que la etiqueta del Path del Registro no esté vacía

            # show the message
            tkinter.messagebox.showerror(title="Record Path emply", message="Please, enter a valid Value")
            return 0


        elif F3 == "":                          # Validación que la caja de texto de Frecuencia Mínima del filtro Paso-Banda no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Minimum Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        elif F4 == "":                          # Validación que la caja de texto de Frecuencia Maxima del filtro Paso-Banda no esté vacía

            # show the error message
            tkinter.messagebox.showerror(title="Maximum Frequency emply", message="Please, enter a valid Frequency Value")
            pass    # continue

        else:

                F1c = float(F3)                 # Conversión del valor string de la caja de texto Frecuencia Mínima a valor flotante (decimales)
                F1d = float(F4)                 # Conversión del valor string de la caja de texto Frecuencia Maxima a valor flotante (decimales)

                archivoFil1 =etiqueta3.cget("text")

                st  = obspy.read(archivoFil1)                                   # Lectura archivo de acuerdo al formato

                head, tail = os.path.split(archivoFil1)
                root, extension = os.path.splitext(archivoFil1)
                root, extension = os.path.splitext(tail)

                st.filter('bandpass', freqmin=F1c, freqmax=F1d, corners=4, zerophase=True)  # Filtro paso Banda de orden 4

                st.plot(color='blue')

    except:
                tkinter.messagebox.showerror(title="Record File or Entry Invalid", message="The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")

                return 0


def Regreso():                                              # Funcion de llamada a otro programa (Regresar)
        if sistema == "Windows":                            # Si el sistema es Windows

            subprocess.Popen(["python", "Menu.py"])        # Llamada al prograna de Indice (Index.py)
            root.destroy()                                  # Se destruye o borra la ventana

        else:                                                               # Si el sistema es Linux

            subprocess.Popen(["python3", "Menu.py"])       # Llamada al prograna de Indice (Index.py)
            root.destroy()                                  # Se destruye o borra la ventana

def limpiarCampos():        # Función para limpiar las entradas

    MsgBox = messagebox.askquestion(message="Are you sure to delete all entries?", title="Clean all inputs", default="yes")

    if MsgBox == 'yes':                                     # If the answer is OK

            # Elimina el texto completo.
            etiqueta3.config(text='')

            # Se eliminan las entradas de la caja de texto 1 para la Magnitud
            # Elimina el texto completo.
            caja1.delete(0, tk.END)

            # Valor por defecto para la caja1: Magnitud
            caja1.insert(0, "6.5")

            # Se eliminan las entradas de la caja de texto 2 para la Frecuencia
            # Elimina el texto completo.
            caja2.delete(0, tk.END)

            # Se eliminan las entradas de la caja de texto 3 para la Frecuencia Mínima
            # Elimina el texto completo.
            caja3.delete(0, tk.END)

            # Se eliminan las entradas de la caja de texto 4 para la Frecuencia Maxima
            # Elimina el texto completo.
            caja4.delete(0, tk.END)

            # Se activa la caja de texto Frecuencia
            caja2.config(state=tk.NORMAL)

            # Se desactiva la caja de texto Magnitud
            caja1.config(state=tk.DISABLED)

            # Se desactiva la caja de texto Frecuencia Mínima
            caja3.config(state=tk.DISABLED)

            # Se desactiva la caja de texto Frecuencia Maxima
            caja4.config(state=tk.DISABLED)

            # Se selecciona el Radio Button 1 (lowpass)
            selec.set(1)  # initializing the choice, i.e. Lowpass

    else:
        pass


def salida():               # Función para la Salida del Sistema

    # Se crea la ventana de dialogo (Yes/NO), por defecto se encuentra en "NO"
    MsgBox = messagebox.askquestion(message="Are you sure to exit the Module 3 and System?", title="Exit Module 3 - 24-hour", default="no")

    if MsgBox == 'yes':
        #print('Esta es la salida del sistema')
        root.destroy()
    else:
        #print('Esta NO es la salida del sistema')
        tk.messagebox.showinfo('Welcome Back','Welcome back to the Continuous Day Module')

# Funciones para controlar la selección de los Radio Button

def select_lowpass():                           # Activaciones y borrados de cajas de texto Para el filtro de Paso-Bajo

    # Se activa la caja de texto Frecuencia
    caja2.config(state=tk.NORMAL)

    # Se eliminan las entradas de la caja de texto 3 para la Frecuencia Mínima
    # Elimina el texto completo.
    caja3.delete(0, tk.END)

    # Se eliminan las entradas de la caja de texto 3 para la Frecuencia Máxima
    # Elimina el texto completo.
    caja4.delete(0, tk.END)

    # Se desactiva la caja de texto Frecuencia Mínima
    caja3.config(state=tk.DISABLED)

    # Se desactiva la caja de texto Frecuencia Maxima
    caja4.config(state=tk.DISABLED)


def select_highpass():                      # Activaciones y borrados de cajas de texto Para el filtro de Paso-Alto

    # Se activa la caja de texto Frecuencia
    caja2.config(state=tk.NORMAL)

    # Se eliminan las entradas de la caja de texto 3 para la Frecuencia Mínima
    # Elimina el texto completo.
    caja3.delete(0, tk.END)

    # Se eliminan las entradas de la caja de texto 3 para la Frecuencia Maxima
    # Elimina el texto completo.
    caja4.delete(0, tk.END)

    # Se desactiva la caja de texto Frecuencia Mínima
    caja3.config(state=tk.DISABLED)

    # Se desactiva la caja de texto Frecuencia Maxima
    caja4.config(state=tk.DISABLED)


def select_bandpass():                  # Activaciones y borrados de cajas de texto Para el filtro de Paso-Banda

    # Se activa la caja de texto Frecuencia Mínima
    caja3.config(state=tk.NORMAL)

    # Se activa la caja de texto Frecuencia Maxima
    caja4.config(state=tk.NORMAL)

    # Se eliminan las entradas de la caja de texto 2 para la Frecuencia
    # Elimina el texto completo.
    caja2.delete(0, tk.END)

    # Se desactiva la caja de texto Frecuencia
    caja2.config(state=tk.DISABLED)


# Contrucción de Radio Buttons para los filtros

selec = IntVar() # Se establece la variable para capturar el valor del indice del radiobutton

selec.set(1)  # initializing the choice, i.e. Lowpass

Lowpass_radiobuton = Radiobutton(
            root,
            text="Lowpass",
            value=1,
            variable=selec,
            command=select_lowpass,
        )

Lowpass_radiobuton.place(x=20, y=170)   # Ubicación en la pantalla

Highpass_radiobuton = Radiobutton(
            root,
            text="Highpass",
            value=2,
            variable=selec,
            command=select_highpass,
        )

Highpass_radiobuton.place(x=20, y=200)  # Ubicación en la pantalla

Bandpass_radiobuton = Radiobutton(
            root,
            text="Bandpass",
            value=3,
            variable=selec,
            command=select_bandpass,
        )

Bandpass_radiobuton.place(x=20, y=230)  # Ubicación en la pantalla

def Boton_graficar():  # Función para el botón de "Full day Chart" - Grafica de 24 horas - De acuerdo a la selección del Filtro

    if selec.get()==1:      # Se ha seleccionado el radio button de Filtro Paso-Bajo
        #print('Se ha seleccionado el radio button de Filtro Paso-Bajo')
        grafica24_FiltroPB()

    elif selec.get()==2:    # Se ha seleccionado el radio button de Filtro Paso-Alto
        #print('Se ha seleccionado el radio button de Filtro Paso-Alto')
        grafica24_FiltroPA()

    elif selec.get()==3:    # Se ha seleccionado el radio button de Filtro Paso-Banda
        #print('Se ha seleccionado el radio button de Filtro Paso-Banda')
        grafica24_FiltroPD()
    else:
        pass

def Boton_graficar2():  # Función para el botón de "Continuos" - Grafica Continua - De acuerdo a la selección del Filtro

    if selec.get()==1:      # Se ha seleccionado el radio button de Filtro Paso-Bajo
        #print('Se ha seleccionado el radio button de Filtro Paso-Bajo')
        grafica_FiltroPB()

    elif selec.get()==2:    # Se ha seleccionado el radio button de Filtro Paso-Alto
        #print('Se ha seleccionado el radio button de Filtro Paso-Alto')
        grafica_FiltroPA()

    elif selec.get()==3:    # Se ha seleccionado el radio button de Filtro Paso-Banda
        #print('Se ha seleccionado el radio button de Filtro Paso-Banda')
        grafica_FiltroPD()
    else:
        pass


# Configuración de los botones de Comando
# Función para los parámetros del texto tooltip en los botones

# Boton1 = Cargar el Registro
boton1 = tk.Button(root, text="Load Record", image = img, foreground="blue", background="honeydew", compound = "top", command=cargar)
boton1.place(x=35, y=40, width=100, height=60)
TollTip1 = Hovertip(boton1,"Load Record", hover_delay=1000)
#Hovertip(boton1, text="Load Record", hover_delay=500)

# Boton2 = Botón para graficar el día de 24 horas
boton2 = tk.Button(root, image = img1, text="Full day Chart",  foreground="black", background="lightblue", compound = "top", command=Boton_graficar)
boton2.place(x=500, y=181, width=100, height=60)
TollTip2 = Hovertip(boton2,"Full day Chart", hover_delay=1000)

# Boton3 = Botón para graficar el día dcontinuo
boton3 = tk.Button(root, text="Continuous Day", image = img4, foreground="blue", background="honeydew", compound = "top", command=Boton_graficar2)
boton3.place(x=650, y=181, width=100, height=60)
TollTip3 = Hovertip(boton3,"Continuous Day", hover_delay=1000)

# Boton4 = Botón para limpiar entradas
boton4 = tk.Button(root, text="Clean Inputs", image = img5, foreground="blue", background="bisque", compound = "top", command=limpiarCampos)
boton4.place(x=700, y=40, width=100, height=60)
TollTip4 = Hovertip(boton4,"Clean Inputs", hover_delay=1000)

# Boton5 = Botón para regresar al indice
boton5 = tk.Button(root, text="Go Back", image = img6, foreground="white", background="CornflowerBlue", compound = "top", command=Regreso)
boton5.place(x=20, y=310, width=90, height=58)
TollTip5 = Hovertip(boton5,"Go Back", hover_delay=1000)

# Boton6 = Botón para Salir
boton6 = tk.Button(root, text="Exit", image = img7, foreground="blue", background="tan", compound = "top", command=salida)
boton6.place(x=720, y=310, width=90, height=58)
TollTip6 = Hovertip(boton6," Exit ", hover_delay=1000)

root.mainloop()

# Developed by: Ligdamis A. Gutiérrez E. PhD.


