# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System / Seismic Signal Integration module

# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Andalusian Institute of Geophysics.
# Granada University, (Ugr), Spain, 2021 - 2022

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 5 - Integrals_1.py -> Seismic Signal Integration

# Interface, for Seismic Signal Integration with filters.


# Load libraries to use

# For system use, threads and paths (path)
import sys
import os
import subprocess
from pathlib import Path

# Identify the operating system
import platform
sistema = platform.system()  # Identify the operating system

# Libraries for the use of PyQt5 - binding of the graphical Qt library
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets, uic

from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton
from PyQt5.QtCore import QCoreApplication

import warnings  # Library for alerts

# Libraries for use of Wavelet Transform
# To read records through the "obspy" library
import obspy
from obspy.imaging.cm import obspy_sequential
from obspy.signal.tf_misfit import cwt
from obspy import Stream
from obspy import read
from obspy.io.sac import SACTrace
from obspy import read, Trace

# Libraries for graphics using matplotlib and using numpy, plotly
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure

# import matplotlib.cbook as cbook
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from scipy import integrate
from scipy.integrate import cumtrapz

# Libraries to use tkinter (Graphical interface)
import tkinter
import tkinter as tk
from tkinter.ttk import Combobox, Style
from tkinter import Frame, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT

# In case of using the window as root (changes later)
from tkinter import *
root = tk.Tk()
root.withdraw()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(829, 357)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")

        self.frame_2 = QtWidgets.QFrame(MainWindow)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 811, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        """ --- Values for Comman Buttons (pushButton) Frame 2 --- """

        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 20, 91, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Load.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 80, 91, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Clean.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")

        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 10, 211, 101))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 255, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_2.setPalette(palette)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")

        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 20, 191, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")


        """ --- Values for Text Boxes (lineEdit) Frame 2 --- """

        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)                       # Frequency Text box.
        self.lineEdit.setGeometry(QtCore.QRect(540, 20, 71, 20))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)                     # Minimum frequency text box. / (Min. Time).
        self.lineEdit_2.setGeometry(QtCore.QRect(490, 60, 61, 20))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)                     # Maximum frequency text box. / (Max Time).
        self.lineEdit_3.setGeometry(QtCore.QRect(490, 90, 61, 20))
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_2)                     # Filter Order Text box.
        self.lineEdit_4.setGeometry(QtCore.QRect(570, 90, 61, 20))
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)                     # Trace No. st[0] Text box.
        self.lineEdit_5.setGeometry(QtCore.QRect(750, 80, 41, 21))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")

        """ --- Values for Text Labels (Label) Frame 2 --- """

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(420, 20, 101, 16))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(400, 60, 91, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(400, 90, 91, 16))
        self.label_6.setObjectName("label_6")

        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(700, 10, 71, 61))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Images/Ugr.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(660, 70, 81, 20))
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(670, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")

        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(570, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(570, 60, 71, 16))
        self.label_19.setObjectName("label_19")


        """ --- Values for the separation lines on the canvas (line) Frame 2 --- """

        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(390, 0, 20, 121))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(640, 0, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(140, 0, 20, 121))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setGeometry(QtCore.QRect(0, 60, 151, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_6 = QtWidgets.QFrame(self.frame_2)
        self.line_6.setGeometry(QtCore.QRect(553, 50, 20, 71))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_11 = QtWidgets.QFrame(self.frame_2)
        self.line_11.setGeometry(QtCore.QRect(800, 0, 20, 121))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.line_12 = QtWidgets.QFrame(self.frame_2)
        self.line_12.setGeometry(QtCore.QRect(400, 40, 251, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")


        self.label_3 = QtWidgets.QLabel(MainWindow)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.frame_3 = QtWidgets.QFrame(MainWindow)
        self.frame_3.setGeometry(QtCore.QRect(10, 280, 811, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(150, 0, 3, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(660, 0, 3, 61))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(800, 0, 16, 61))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 10, 111, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/Integral_1.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")

        self.line_14 = QtWidgets.QFrame(self.frame_3)
        self.line_14.setGeometry(QtCore.QRect(290, 0, 3, 61))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")

        self.line_16 = QtWidgets.QFrame(self.frame_3)
        self.line_16.setGeometry(QtCore.QRect(520, 0, 3, 61))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")


        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 10, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_5.setPalette(palette)
        self.pushButton_5.setAutoFillBackground(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/Back.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(680, 10, 101, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setObjectName("pushButton_6")

        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(170, 20, 101, 41))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/Integral.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(330, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(160, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")

        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(220, 190, 601, 71))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 581, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.label.setObjectName("label")

        self.line_9 = QtWidgets.QFrame(MainWindow)
        self.line_9.setGeometry(QtCore.QRect(10, 260, 811, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.label_10 = QtWidgets.QLabel(MainWindow)
        self.label_10.setGeometry(QtCore.QRect(50, 180, 111, 81))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")

        self.label_9 = QtWidgets.QLabel(MainWindow)
        self.label_9.setGeometry(QtCore.QRect(380, 140, 311, 51))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Action Buttons
        self.pushButton.setStyleSheet("background-color: honeydew; color: blue")            # Button color and text (Load File)
        self.pushButton_2.setStyleSheet("background-color: gold; color: blue")              # Button Color and Text (Clear entries)
        self.pushButton_3.setStyleSheet("background-color: silver; color: blue")            # Button color and text (Plot integrals)
        self.pushButton_5.setStyleSheet("background-color: CornflowerBlue; color: white")   # Button Color and Text (Go Back)
        self.pushButton_6.setStyleSheet("background-color: burlywood; color: blue")         # Button color and text (Exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Seismic Signals Integration - University of Granada (Ugr)"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Search Register</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", " Load Record"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filter type"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Please select"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Please Select"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Lowpass "))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Highpass "))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Bandpass "))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Bandstop "))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; color:#aa5500;\">Frecuency (Hz):</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#aa5500;\">Frec Min (Hz):</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#aa5500;\">Frec Max (Hz):</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">Clean Input</span></p></body></html>"))
        self.pushButton_2.setText(_translate("MainWindow", " Clean"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; color:#610000;\">Trace number st(n):</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; font-style:italic; color:#00007f;\">By default: st(0)</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#aa5500;\">Filter Order</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; font-style:italic; color:#00007f;\">By default = 4</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">Seismic Signal Integration</span></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">Single Integral</span></p></body></html>"))
        self.pushButton_3.setText(_translate("MainWindow", "  Plot Integral"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#aa0000;\">Records Action Commands</span></p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">System Exit</span></p></body></html>"))
        self.pushButton_6.setText(_translate("MainWindow", "  Exit"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Back to Index</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "  Go Back"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-style:italic; color:#0000ff;\">Seismic Signal Integral Equation:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Register path to load:  </span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#00007f;\">The &quot;obspy&quot; library is used to read the seismic records, </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#00007f;\">The&quot;cumtrapz&quot; function is defined for integrate the signal. </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic; color:#00007f;\">The matplolib library is used for the graphs.</span></p></body></html>"))

        # Disable text boxes initially
        self.lineEdit.setEnabled(False)                                         # Disables the Frequency Text box.
        self.lineEdit_2.setEnabled(False)                                       # Disables the minimum frequency text box. / (Min. Time).
        self.lineEdit_3.setEnabled(False)                                       # Disables the maximum frequency text box. / (Max Time).
        self.lineEdit_4.setEnabled(False)                                       # Disables the Filter Order Text box.
        self.lineEdit_5.setEnabled(False)                                       # Disables the Trace No. st[0] Text box.

        # Command button actions, function calls
        self.pushButton.clicked.connect(self.open_file1)                        # Call the function to upload file (Load File).
        self.pushButton_2.clicked.connect(self.limpiar_entradas)                # Calls the function to clean entries (Clean Entries).
        self.pushButton_3.clicked.connect(self.verificar)                       # Calls the function to signal integral.
        self.pushButton_5.clicked.connect(self.return1)                         # Call the function to return to the Home Screen (Back).
        self.pushButton_6.clicked.connect(self.Exit1)                           # Call the function to exit the System (Exit).

        # Enable / Disable buttons for graphing (Disabled at startup)
        self.pushButton_3.setEnabled(False)                                     # Disable the Plot button for the Single Integral.

        self.lineEdit_4.setText("4")                                            # By default, initially the order filter = 4

        # By default, initially No. Trace = 0
        self.lineEdit_5.setText("0")                                            # By default, initially the Trace No. st[0] Text box.

        # Call to the function according to the ComboBox list for the Filter type
        self.comboBox_2.activated.connect(self.selection_changed1)


    """ ------------- Start of Program Functions  ------------ """

    """ Function to open and clean """

    """  Function to manage the filter combobox  """

    def selection_changed1(self):  # Function that programs the list of the ComboBox, for the Type of Filter

        index = self.comboBox_2.currentIndex()                                  # According to the selection of the combo, its index is captured

        # Activation/Deactivation buttons for graphing
        self.pushButton_3.setEnabled(True)                                      # Activate the Graph button for the integral of the signal.

        if (0 == index):                                                        # In case the Combobox index is 0, "Select"
            plt.close()                                                         # Close the existing chart.
            plt.close()                                                         # Close the existing chart.
            self.activacion1()                                                  # Call to the cleaning function and Activation/Deactivation

        elif (1 == index):                                                      # In case the Combobox index is 1, Lowpass Filter
            plt.close()                                                         # Close the existing chart.
            plt.close()                                                         # Close the existing chart.
            self.activacion2()                                                  # Call to the cleaning function and Activation/Deactivation

        elif (2 == index):                                                      # In case the Combobox index is 2, Highpass Filter
            plt.close()                                                         # Close the existing chart.
            plt.close()                                                         # Close the existing chart.
            self.activacion2()                                                  # Call to the cleaning function and Activation/Deactivation

        elif (3 == index):                                                      # In case the Combobox index is 3, Bandpass Filter
            plt.close()                                                         # Close the existing chart.
            plt.close()                                                         # Close the existing chart.
            self.activacion3()                                                  # Call to the cleaning function and Activation/Deactivation

        elif (4 == index):                                                      # In case the Combobox index is 4, Bandstop Filter
            plt.close()                                                         # Close the existing chart.
            plt.close()                                                         # Close the existing chart.
            self.activacion3()                                                  # Call to the cleaning function and Activation/Deactivation

        else:
            pass


    def open_file1(self):                                                       # Function, to search and load the records according to the format

        if sistema == "Windows":
            #print("Sistema Windows")

            self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('NPY Files','*.npy'),
                ('EVT Files','*.evt')))

            self.ruta = Path(self.archivo_abierto)
            self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_2.setFont(font)                  # Printing using text format.
            self.label_2.setText(self.archivo_abierto)  # Printing on the file path label.

        else:

            self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('NPY Files','*.npy'),
                ('EVT Files','*.evt')))

            self.ruta = Path(self.archivo_abierto)
            self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_2.setFont(font)                  # Printing using text format.
            self.label_2.setText(self.archivo_abierto)  # Printing on the file path label.

            return self

    def limpiar_entradas(self):                                                 # Clean and leave everything as at the beginning.

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Clean all inputs.")
        msg.setText("Are you sure to delete all entries?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                    # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                       # If the answer is OK

            # Position the ComboBox at the start.
            self.comboBox_2.setCurrentIndex(0)                                      # Position in the first Item (Filter Type)
            plt.close()                                                             # Close the existing chart.
            plt.close()                                                             # Close the existing chart.

            # Delete label content and Text Boxes.
            self.label_2.setText("")                                                # Delete the contents of the File Path label
            self.lineEdit.setText("")                                               # Clear the content of the Frequency text box
            self.lineEdit_2.setText("")                                             # Clear the content of the minimum frequency text box
            self.lineEdit_3.setText("")                                             # Clear the content of the maximum frequency text box
            self.lineEdit_4.setText("4")                                            # Clear and by default, initially the order filter = 4
            self.lineEdit_5.setText("0")                                            # By default, initially the Trace No. st[0] Text box.

            # Disable text boxes
            self.lineEdit.setEnabled(False)                                         # Deactivate the Frequency Text box.
            self.lineEdit_2.setEnabled(False)                                       # Disables the minimum frequency text box. / (Min. Time).
            self.lineEdit_3.setEnabled(False)                                       # Disables the maximum frequency text box. / (Max Time).
            self.lineEdit_4.setEnabled(False)                                       # Deactivate the Filter Order Text box.
            self.lineEdit_5.setEnabled(False)                                       # Disables the Trace No. st[0] Text box.

            plt.close()                                                             # Close the existing chart.
            plt.close()                                                             # Close the existing chart.

        else:
            pass

    """ Function to handle the activation / deactivation of text boxes in filters  """

    def activacion1(self):                                                      # To Activate / Deactivate and cleaning in "Selection" -> Index 0.

        plt.close()                                                             # Close the existing chart.

        # Clean entrances.
        self.lineEdit.setText("")                                               # Clear the content of the Frequency text box.
        self.lineEdit_2.setText("")                                             # Clear the content of the minimum frequency text box.
        self.lineEdit_3.setText("")                                             # Clear the content of the maximum frequency text box.
        self.lineEdit_4.setText("4")                                            # Clear and by default, initially the order filter = 4
        self.lineEdit_5.setText("0")                                            # By default, initially the Trace No. st[0] Text box.


        # Enable and disable input text boxes.
        self.lineEdit.setEnabled(False)                                         # Disable the Frequency Text box.
        self.lineEdit_2.setEnabled(False)                                       # Disable the minimum frequency text box.
        self.lineEdit_3.setEnabled(False)                                       # Disable the maximum frequency text box.
        self.lineEdit_4.setEnabled(False)                                       # Disable the Filter Order text box.
        self.lineEdit_5.setEnabled(False)                                       # Disables the Trace No. st[0] Text box.

        plt.close()                                                             # Close the existing chart.


    def activacion2(self):                                                      # To Activate / Deactivate and cleaning in Lowpass y Highpass

        plt.close()                                                             # Close the existing chart.

        # Clean entrances.
        self.lineEdit_2.setText("")                                             # Clear the content of the minimum frequency text box.
        self.lineEdit_3.setText("")                                             # Clear the content of the maximum frequency text box.
        #self.lineEdit_4.setText("")                                            # Clear the content of the Filter Order text box.

        # Activa/Desactiva cajas de texto
        self.lineEdit.setEnabled(True)                                          # Activate the Frequency Text box.
        self.lineEdit_2.setEnabled(False)                                       # Disable the minimum frequency text box.
        self.lineEdit_3.setEnabled(False)                                       # Disable the maximum frequency text box.
        self.lineEdit_4.setEnabled(True)                                        # Activate the Filter Order text box.
        self.lineEdit_5.setEnabled(True)                                        # Activate the Trace No. st[0] Text box.

        plt.close()                                                             # Close the existing chart.

    def activacion3(self):                  # To Activate / Deactivate and cleaning in Bandpass y Bandstop

        plt.close()                                                             # Close the existing chart.

        # Clean entrances.
        self.lineEdit.setText("")                                               # Clear the content of the Frequency text box.

        # Enable and disable input text boxes.
        self.lineEdit.setEnabled(False)                                         # Disable the Frequency Text box.
        self.lineEdit_2.setEnabled(True)                                        # Activate the minimum frequency text box.
        self.lineEdit_3.setEnabled(True)                                        # Activate the maximum frequency text box.
        self.lineEdit_4.setEnabled(True)                                        # Activate the Filter Order text box.
        self.lineEdit_5.setEnabled(True)                                        # Activate the Trace No. st[0] Text box.

        plt.close()                                                             # Close the existing chart.


    """  *** Functions to perform analysis with filters (1-4) ***     """

    def filtropasobajo(self):               # 1.- Function to execute the Lowpass filter

        try:

            # Verify that the Frequency text box is not empty
            if not self.lineEdit.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Frequency")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            # Verify that the Filter Order text box is not empty
            elif not self.lineEdit_4.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Filter Order")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            # Verify that the Trace No. st[0] Text box is not empty
            elif not self.lineEdit_5.text():
                MensCombo3 = QMessageBox()
                MensCombo3.setIcon(QMessageBox.Warning)
                MensCombo3.setWindowTitle("Empty Trace No.")
                MensCombo3.setText("Please enter a valid value")
                returnValue = MensCombo3.exec()


            else:
                # Filtering with a lowpass.
                plt.close()                                                     # Close the existing chart.

                self.lineEdit_2.setText("")                                     # Clear the content of the minimum frequency text box.
                self.lineEdit_3.setText("")                                     # Clear the content of the maximum frequency text box.

                archivoFil1 = (self.label_2.text())                             # Reading the label that contains the record

                frec1 = (self.lineEdit.text())                                  # Reading the label that contains the frequency
                orden1 = (self.lineEdit_4.text())                               # Reading the label that contains the order filter

                st  = obspy.read(archivoFil1)                                   # Reading the file according to the format through the Obspy library

                # Convert to numbers (integer and float), the string value of the text box
                frec2=float(frec1)                                              # Convert the string value of Frequency to a float number
                orden2=int(orden1)                                              # Convert the string value of filter order to a int number

                # Enter and convert to integer the string value of the No. Traces st[0] text box
                NTraza = (self.lineEdit_5.text())                               # Reading the content of the text box Trace No. st[0]
                Ntraza2 = int(NTraza)                                           # Converts the value of the Trace Number to integer
                tr = st[Ntraza2]                                                # Assigns the indicated trace number to the Stream for record processing

                tr.stats.station

                cabecera = st[Ntraza2].stats

                tr_filt = tr.copy()
                s = len(tr)

                Y = tr_filt.filter('lowpass', freq=frec2, corners=orden2, zerophase=True)
                # Where corners = filter order, by default order 4

                t1 = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                dt = 1/tr.stats.sampling_rate

                s = len(tr)

                t = np.arange(1,s)*dt

                y = integrate.cumtrapz(tr)*dt                                   # Integrate with original signal

                y2 = integrate.cumtrapz(Y)*dt                                   # Integrate with filtered signal

                plt.close()                                                     # Close the existing chart.
                ax = plt.subplot(311)
                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.title('Seismic Signal Integration')
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.grid()

                plt.subplot(312, sharex=ax)
                plt.plot(t1,Y,color ="darkgreen", label='Lowpass Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()

                plt.subplot(313, sharex=ax)
                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.xlabel('Time(seg)',color ="red")
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()
                # En caso de colocar la leyenda dentro del gráfico
                # labels
                #a=1.5
                #b=9.5
                #plt.text(8.5*(a+b),10.5,r"$\int v(t)dt$",horizontalalignment='center',fontsize=10)

                plt.figure()

                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Original Record')
                plt.grid()

                plt.figure()

                plt.plot(t1,Y,color ="darkgreen", label='Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Lowpass Filtred Record')
                plt.grid()

                plt.figure()

                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('v(t) Integral')
                plt.grid()

                plt.show()


        except:

                plt.close()                                                     # close the existing chart
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Doesn't exist, is Invalid or the Format is not recognized. please try again...")
                msgBox.setWindowTitle("Invalid Format Record or parameters values")
                returnValue = msgBox.exec()


    def filtropasoalto(self):               # 2.- Function to execute the Highpass filter

        try:

            # Verify that the Frequency text box is not empty
            if not self.lineEdit.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Frequency")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            # Verify that the Filter Order text box is not empty
            elif not self.lineEdit_4.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Filter Order")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            # Verify that the Trace No. st[0] Text box is not empty
            elif not self.lineEdit_5.text():
                MensCombo3 = QMessageBox()
                MensCombo3.setIcon(QMessageBox.Warning)
                MensCombo3.setWindowTitle("Empty Trace No.")
                MensCombo3.setText("Please enter a valid value")
                returnValue = MensCombo3.exec()


            else:
                # Filtering with a Highpass.
                plt.close()                                                     # Close the existing chart.

                self.lineEdit_2.setText("")                                     # Clear the content of the minimum frequency text box.
                self.lineEdit_3.setText("")                                     # Clear the content of the maximum frequency text box.

                archivoFil1 = (self.label_2.text())                             # Reading the label that contains the record

                frec1 = (self.lineEdit.text())                                  # Reading the label that contains the frequency
                orden1 = (self.lineEdit_4.text())                               # Reading the label that contains the order filter

                st  = obspy.read(archivoFil1)                                   # Reading the file according to the format through the Obspy library

                # Convert to numbers (integer and float), the string value of the text box
                frec2=float(frec1)                                              # Convert the string value of Frequency to a float number
                orden2=int(orden1)                                              # Convert the string value of filter order to a int number

                # Enter and convert to integer the string value of the No. Traces st[0] text box
                NTraza = (self.lineEdit_5.text())                               # Reading the content of the text box Trace No. st[0]
                Ntraza2 = int(NTraza)                                           # Converts the value of the Trace Number to integer
                tr = st[Ntraza2]                                                # Assigns the indicated trace number to the Stream for record processing

                tr.stats.station

                cabecera = st[Ntraza2].stats

                tr_filt = tr.copy()
                s = len(tr)

                Y = tr_filt.filter('highpass', freq=frec2, corners=orden2, zerophase=True)
                # Where corners = filter order, by default order 4

                t1 = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                dt = 1/tr.stats.sampling_rate

                s = len(tr)

                t = np.arange(1,s)*dt

                y = integrate.cumtrapz(tr)*dt                                   # Integrate with original signal

                y2 = integrate.cumtrapz(Y)*dt                                   # Integrate with filtered signal

                plt.close()                                                     # Close the existing chart.
                ax = plt.subplot(311)
                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.title('Seismic Signal Integration')
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.grid()

                plt.subplot(312, sharex=ax)
                plt.plot(t1,Y,color ="darkgreen", label='Highpass Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()

                plt.subplot(313, sharex=ax)
                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.xlabel('Time(seg)',color ="red")
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()
                # En caso de colocar la leyenda dentro del gráfico
                # labels
                #a=1.5
                #b=9.5
                #plt.text(8.5*(a+b),10.5,r"$\int v(t)dt$",horizontalalignment='center',fontsize=10)

                plt.figure()

                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Original Record')
                plt.grid()

                plt.figure()

                plt.plot(t1,Y,color ="darkgreen", label='Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Highpass Filtred Record')
                plt.grid()

                plt.figure()

                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('v(t) Integral')
                plt.grid()

                plt.show()

        except:

                plt.close()                                                     # close the existing chart
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Doesn't exist, is Invalid or the Format is not recognized. please try again...")
                msgBox.setWindowTitle("Invalid Format Record or parameters values")
                returnValue = msgBox.exec()

    def filtropasabanda(self):               # 3.- Function to execute the Bandpass filter

        try:

            # Verify that the text boxes of the Minimum, Maximum Frequencies, filter order and Trace No. st[0] are not empty
            if not self.lineEdit_2.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Frequency Min.")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            elif not self.lineEdit_3.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Frequency Max.")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            # Verify that the Filter Order text box is not empty
            elif not self.lineEdit_4.text():
                MensCombo3 = QMessageBox()
                MensCombo3.setIcon(QMessageBox.Warning)
                MensCombo3.setWindowTitle("Empty Filter Order")
                MensCombo3.setText("Please, enter a valid Value")
                returnValue = MensCombo3.exec()

            # Verify that the Trace No. st[0] Text box is not empty
            elif not self.lineEdit_5.text():
                MensCombo4 = QMessageBox()
                MensCombo4.setIcon(QMessageBox.Warning)
                MensCombo4.setWindowTitle("Empty Trace No.")
                MensCombo4.setText("Please enter a valid value")
                returnValue = MensCombo4.exec()

            else:
                # Filtering with a Bandpass.
                plt.close()                                                     # Close the existing chart.

                self.lineEdit.setText("")                                       # Clear the content of the frequency text box.

                archivoFil1 = (self.label_2.text())                             # Reading the label that contains the record

                orden1 = (self.lineEdit_4.text())                               # Reading the label that contains the order filter
                frecM = (self.lineEdit_2.text())                                # Lectura etiqueta de Frec. Min.
                frecMax = (self.lineEdit_3.text())                              # Lectura etiqueta de Frec. Max.

                st  = obspy.read(archivoFil1)                                   # Reading the file according to the format through the Obspy library

                # Convert to numbers (integer and float), the string value of the text box
                frec7=float(frecM)                                              # Convert the string value of Min. Frequency to a float number
                frec8=float(frecMax)                                            # Convert the string value of Max. Frequency to a float number.
                orden7=int(orden1)                                              # Convert the string value of filter order to a int number.

                # Enter and convert to integer the string value of the No. Traces st[0] text box
                NTraza = (self.lineEdit_5.text())                               # Reading the content of the text box Trace No. st[0]
                Ntraza2 = int(NTraza)                                           # Converts the value of the Trace Number to integer
                tr = st[Ntraza2]                                                # Assigns the indicated trace number to the Stream for record processing

                tr.stats.station

                cabecera = st[Ntraza2].stats

                tr_filt = tr.copy()
                s = len(tr)

                Y = tr_filt.filter('bandpass', freqmin=frec7, freqmax=frec8, corners=orden7, zerophase=True)
                # Where corners = filter order, by default order 4

                t1 = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                dt = 1/tr.stats.sampling_rate

                s = len(tr)

                t = np.arange(1,s)*dt

                y = integrate.cumtrapz(tr)*dt                                   # Integrate with original signal

                y2 = integrate.cumtrapz(Y)*dt                                   # Integrate with filtered signal

                plt.close()                                                     # Close the existing chart.
                ax = plt.subplot(311)
                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.title('Seismic Signal Integration')
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.grid()

                plt.subplot(312, sharex=ax)
                plt.plot(t1,Y,color ="darkgreen", label='Bandpass Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()

                plt.subplot(313, sharex=ax)
                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.xlabel('Time(seg)',color ="red")
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()
                # En caso de colocar la leyenda dentro del gráfico
                # labels
                #a=1.5
                #b=9.5
                #plt.text(8.5*(a+b),10.5,r"$\int v(t)dt$",horizontalalignment='center',fontsize=10)

                plt.figure()

                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Original Record')
                plt.grid()

                plt.figure()

                plt.plot(t1,Y,color ="darkgreen", label='Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Bandpass Filtred Record')
                plt.grid()

                plt.figure()

                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('v(t) Integral')
                plt.grid()

                plt.show()

        except:

                plt.close()                                                     # close the existing chart
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Doesn't exist, is Invalid or the Format is not recognized. please try again...")
                msgBox.setWindowTitle("Invalid Format Record or parameters values")
                returnValue = msgBox.exec()

    def filtrobandstop(self):               # 4.- Function to execute the Bandstop filter

        try:

            # Verify that the text boxes of the Minimum, Maximum Frequencies, filter order and Trace No. st[0] are not empty
            if not self.lineEdit_2.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Frequency Min.")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            elif not self.lineEdit_3.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Frequency Max.")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            # Verify that the Filter Order text box is not empty
            elif not self.lineEdit_4.text():
                MensCombo3 = QMessageBox()
                MensCombo3.setIcon(QMessageBox.Warning)
                MensCombo3.setWindowTitle("Empty Filter Order")
                MensCombo3.setText("Please, enter a valid Value")
                returnValue = MensCombo3.exec()

            # Verify that the Trace No. st[0] Text box is not empty
            elif not self.lineEdit_5.text():
                MensCombo4 = QMessageBox()
                MensCombo4.setIcon(QMessageBox.Warning)
                MensCombo4.setWindowTitle("Empty Trace No.")
                MensCombo4.setText("Please enter a valid value")
                returnValue = MensCombo4.exec()

            else:
                # Filtering with a Bandstop.
                plt.close()                                                     # Close the existing chart.

                self.lineEdit.setText("")                                       # Clear the content of the frequency text box.

                archivoFil1 = (self.label_2.text())                             # Reading the label that contains the record

                orden8 = (self.lineEdit_4.text())                               # Reading the label that contains the order filter
                frecM = (self.lineEdit_2.text())                                # Lectura etiqueta de Frec. Min.
                frecMax = (self.lineEdit_3.text())                              # Lectura etiqueta de Frec. Max.

                st  = obspy.read(archivoFil1)                                   # Reading the file according to the format through the Obspy library

                # Convert to numbers (integer and float), the string value of the text box
                frec9=float(frecM)                                              # Convert the string value of Min. Frequency to a float number
                frec10=float(frecMax)                                            # Convert the string value of Max. Frequency to a float number.
                orden9=int(orden8)                                              # Convert the string value of filter order to a int number.

                # Enter and convert to integer the string value of the No. Traces st[0] text box
                NTraza = (self.lineEdit_5.text())                               # Reading the content of the text box Trace No. st[0]
                Ntraza2 = int(NTraza)                                           # Converts the value of the Trace Number to integer
                tr = st[Ntraza2]                                                # Assigns the indicated trace number to the Stream for record processing

                tr.stats.station

                cabecera = st[Ntraza2].stats

                tr_filt = tr.copy()
                s = len(tr)

                Y = tr_filt.filter('bandstop', freqmin=frec9, freqmax=frec10, corners=orden9, zerophase=True)
                # Where corners = filter order, by default order 4

                t1 = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                dt = 1/tr.stats.sampling_rate

                s = len(tr)

                t = np.arange(1,s)*dt

                y = integrate.cumtrapz(tr)*dt                                   # Integrate with original signal

                y2 = integrate.cumtrapz(Y)*dt                                   # Integrate with filtered signal

                plt.close()                                                     # Close the existing chart.
                ax = plt.subplot(311)
                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.title('Seismic Signal Integration')
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.grid()

                plt.subplot(312, sharex=ax)
                plt.plot(t1,Y,color ="darkgreen", label='Bandstop Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()

                plt.subplot(313, sharex=ax)
                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.xlabel('Time(seg)',color ="red")
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.grid()
                # En caso de colocar la leyenda dentro del gráfico
                # labels
                #a=1.5
                #b=9.5
                #plt.text(8.5*(a+b),10.5,r"$\int v(t)dt$",horizontalalignment='center',fontsize=10)

                plt.figure()

                plt.plot(t1,tr,color ="black", label='Original Record')         # Unfiltered original signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Original Record')
                plt.grid()

                plt.figure()

                plt.plot(t1,Y,color ="darkgreen", label='Filtred Record')       # Filtered signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('Bandstop Filtred Record')
                plt.grid()

                plt.figure()

                plt.plot(t,y2, label='v(t) Integral -> $\int v(t)dt$')          # Integrated signal
                plt.legend(prop = {'size': 10}, loc='upper right')              # To place the legend on the top left
                plt.xlabel('Time(seg)',color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.title('v(t) Integral')
                plt.grid()
                plt.show()

        except:

                plt.close()                                                     # close the existing chart
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Doesn't exist, is Invalid or the Format is not recognized. please try again...")
                msgBox.setWindowTitle("Invalid Format Record or parameters values")
                returnValue = msgBox.exec()

    def verificar(self):                                    # Command button call the Function to validate entries and graph Filters of the seismic record

            index1 = self.comboBox_2.currentIndex()                             # Reading the ComboBox index

            if (1 == index1):                                                   # If the index is equal to 1, call the lowpass filter function
                plt.close()                                                     # Close the existing chart.
                plt.close()                                                     # Close the existing chart.
                self.filtropasobajo()

            elif (2 == index1):                                                 # If the index is equal to 2, call the Highpass filter function
                plt.close()                                                     # Close the existing chart.
                plt.close()                                                     # Close the existing chart.
                self.filtropasoalto()

            elif (3 == index1):                                                 # If the index is equal to 3, call the Bandpass filter function
                plt.close()                                                     # Close the existing chart.
                plt.close()                                                     # Close the existing chart.
                self.filtropasabanda()

            elif (4 == index1):                                                  # If the index is equal to 4, call the Stopband filter function
                plt.close()                                                     # Close the existing chart.
                plt.close()                                                     # Close the existing chart.
                self.filtrobandstop()

            else:
                pass


    """ Function to go back at home """

    def return1(self):   # Call function to another program (Back)
        if sistema == "Windows":                                            # If the system is Windows
            plt.close()                                                     # Close the existing chart.
            subprocess.Popen(["python", "Menu.py"])
            app.quit()
            #print("We are in {}".format(sistema))
        else:                                                               # If the system is Linux
            plt.close()                                                     # Close the existing chart
            subprocess.Popen(["python3", "Menu.py"])
            app.quit()



    """  Fuction to exit system  """

    def Exit1(self):    # Function to show exit dialog box
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Exit System")
        msg.setText("Are you sure to exit the System?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                   # If the answer is OK
            app.closeAllWindows()                                           # Close all windows


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
