# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.

# Andalusian Institute of Geophysics
# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Granada University, (Ugr), Spain, 2021 - 2023

# FEMALE (PID2019-106260GB-I00) and PROOF334 FOREVER (EUR2022.134044) Spanish projects)
# Spanish Project PID2022-143083NB-100 founded by MCIN/AEI/10.13039/501100011033
# and by FEDER (EU) "Unam manera de hacer Europa".

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Menu.py -> Main menu to Reliable set tools in Python Software for the analysis of seismic-volcanic signals.

# Load libraries to use
import sys
import os
import subprocess
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets

# Load and see the operating system
import platform
System1 = platform.system()

# Main Class

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 606)

        # Seleccionar y presentar el icono de la Universidad en la parte izqierda de la barra superior de herramientas,

        icon = QtGui.QIcon()
        # Loading the Ugr image on the canvas
        icon.addPixmap(QtGui.QPixmap(r"Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_Menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_Menu.setGeometry(QtCore.QRect(10, 50, 351, 541))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 212, 183))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)

        # Parámetros de la zona de los botones de comandos para la llamada a  los módulos

        self.frame_Menu.setPalette(palette)
        self.frame_Menu.setAutoFillBackground(True)
        self.frame_Menu.setStyleSheet("Qframe{\n"
            "background-color:rgb(216,30,240);\n"
            "}\n"
            "\n"
            "QPushButton{\n"
            "background-color:rgb(61,61,61);\n"
            "border-top-left-radius:20px;\n"
            "border-bottom-left-radius:20px;\n"
            "color:rgb(255,255,255);\n"
            "font:67 8pt\"Arial Black\";\n"
            "\n"
            "}\n"
            "\n"
            "QPushButton:hover{\n"
            "background-color:white;\n"
            "border-top-left-radius:20px;\n"
            "border-bottom-left-radius:20px;\n"
            "color: rgb(38,30,240);\n"
            "font: 67 8pt\"Arial Black\";\n"
            "}")
        self.frame_Menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Menu.setObjectName("frame_Menu")

        # Listado de botones de comandos y sus parámetros para cada módulo

        self.pushButton = QtWidgets.QPushButton(self.frame_Menu)                # 1.- Analysis of Spectral Characteristics
        self.pushButton.setGeometry(QtCore.QRect(40, 30, 261, 40))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.frame_Menu)              # 2.- STA/LTA triggering methods.
        self.pushButton_2.setGeometry(QtCore.QRect(40, 80, 261, 40))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_Menu)              # 3.- Plotting 24-hour seismic records.
        self.pushButton_3.setGeometry(QtCore.QRect(40, 130, 261, 40))
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_Menu)              # 4.- Coverting Seismic Records to Wav.
        self.pushButton_4.setGeometry(QtCore.QRect(40, 180, 261, 40))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(self.frame_Menu)              # 5.- Integrate Seismic Signals.
        self.pushButton_5.setGeometry(QtCore.QRect(40, 230, 261, 40))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_Menu)              # 6.- Select, cut and save events.
        self.pushButton_6.setGeometry(QtCore.QRect(40, 280, 261, 40))
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_6.setObjectName("pushButton_6")

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_Menu)              # 7.- Select, merge and save events.
        self.pushButton_7.setGeometry(QtCore.QRect(40, 330, 261, 40))
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_7.setObjectName("pushButton_7")

        self.pushButton_8 = QtWidgets.QPushButton(self.frame_Menu)              # 8.- Save Records in MSEED and SAC
        self.pushButton_8.setGeometry(QtCore.QRect(40, 380, 261, 40))
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_8.setObjectName("pushButton_8")

        self.pushButton_9 = QtWidgets.QPushButton(self.frame_Menu)              # 9.- Download  records from the FDSN
        self.pushButton_9.setGeometry(QtCore.QRect(40, 430, 261, 40))
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setObjectName("pushButton_9")

        self.pushButton_10 = QtWidgets.QPushButton(self.frame_Menu)             # 10.- Individual Seismic Data Download
        self.pushButton_10.setGeometry(QtCore.QRect(40, 480, 261, 40))
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_10.setObjectName("pushButton_10")

        self.label_2 = QtWidgets.QLabel(self.frame_Menu)
        self.label_2.setGeometry(QtCore.QRect(60, 3, 231, 16))
        self.label_2.setObjectName("label_2")

        # Parámetros para el frame del botón de comandos inferior que permite la salida del sistema.

        self.frame_Botones2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_Botones2.setGeometry(QtCore.QRect(370, 50, 411, 541))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_Botones2.setPalette(palette)
        self.frame_Botones2.setAutoFillBackground(True)
        self.frame_Botones2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Botones2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Botones2.setObjectName("frame_Botones2")

        # Botón de comandos de la salida del sistema

        self.pushButton_12 = QtWidgets.QPushButton(self.frame_Botones2)         # Command Button: "Exit System".
        self.pushButton_12.setGeometry(QtCore.QRect(160, 470, 101, 41))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon)
        self.pushButton_12.setObjectName("pushButton_12")

        # Zona de parámetros de las líneas y las etiquetas que continen las imágenes y mensajes

        self.line_9 = QtWidgets.QFrame(self.frame_Botones2)
        self.line_9.setGeometry(QtCore.QRect(0, 440, 411, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.label_3 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_3.setGeometry(QtCore.QRect(10, 460, 81, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/Ugr.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_4.setGeometry(QtCore.QRect(320, 460, 81, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_5.setGeometry(QtCore.QRect(20, 110, 381, 331))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/Masaya_Volcanoe.JPG"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 381, 81))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/Logodepto.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_7.setGeometry(QtCore.QRect(210, 370, 161, 21))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.frame_Botones2)
        self.label_8.setGeometry(QtCore.QRect(210, 390, 161, 21))
        self.label_8.setObjectName("label_8")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 761, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 226, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 226, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 226, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(235, 226, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")

        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 0, 661, 31))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Command Button - Exit.
        self.pushButton_12.setStyleSheet("background-color: bisque; color: blue")              # Text and Color of the Command Button (Exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reliable set tools in Python Software for the analysis of seismic-volcanic signals -  Granada University (Ugr)"))

        # Parametros de etiquetas para los botones de comandos

        self.pushButton.setText(_translate("MainWindow", "1.- Analysis of Spectral Characteristics"))
        self.pushButton_2.setText(_translate("MainWindow", "2.- STA/LTA triggering methods"))
        self.pushButton_3.setText(_translate("MainWindow", "3.- Plotting 24-hour seismic records"))
        self.pushButton_4.setText(_translate("MainWindow", "4.- Coverting Seismic Records to Wav"))
        self.pushButton_5.setText(_translate("MainWindow", "5.- Integrate Seismic Signals"))
        self.pushButton_6.setText(_translate("MainWindow", "6.- Select, cut and save events"))
        self.pushButton_7.setText(_translate("MainWindow", "7.- Select, merge and save events"))
        self.pushButton_8.setText(_translate("MainWindow", "8.- Save Records in MSEED and SAC"))
        self.pushButton_9.setText(_translate("MainWindow", "9.- Download  records from the FDSN"))
        self.pushButton_10.setText(_translate("MainWindow", "10.- Individual Seismic Data Download"))

        self.pushButton_12.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Exit System</span></p></body></html>"))
        self.pushButton_12.setText(_translate("MainWindow", "  Exit"))

        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#aa0000;\">Reliable set tools in Python Software for the analysis of seismic-volcanic signals.</span></p></body></html>"))

        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; color:#0000ff;\">Please, select your option</span></p></body></html>"))

        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic; color:#ffff00;\">Masaya Volcano - Nic.</span></p></body></html>"))

        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:6pt; font-weight:600; font-style:italic; color:#ffff00;\">Photo by: Ligdamis A. Gtz.</span></p></body></html>"))


        # Command buttons, Call to functions

        self.pushButton.clicked.connect(self.Analysis1)                             # Call the function to run Module 1 (Analysis_System_1)

        self.pushButton_2.clicked.connect(self.STA_LTA)                             # Call the function to run Module 2 (Sta_Lta_trigger_methods)

        self.pushButton_3.clicked.connect(self.Ploting_24hrs)                       # Call the function to run Module 3 (Days_1)

        self.pushButton_4.clicked.connect(self.SonidoWav)                           # Call the function to run Module 4 (Sound_1)

        self.pushButton_5.clicked.connect(self.Integrales)                          # Call the function to run Module 5 (Integrals_1)

        self.pushButton_6.clicked.connect(self.Cortar)                              # Call the function to run Module 6 (Cut_1)

        self.pushButton_7.clicked.connect(self.Fusionar)                            # Call the function to run Module 7 (Merge_1)

        self.pushButton_8.clicked.connect(self.Convertir)                           # Call the function to run Module 8 (Convert_1)

        self.pushButton_9.clicked.connect(self.Descargar_FDSN)                      # Call the function to run Module 9 (Download_FDSN_1)

        self.pushButton_10.clicked.connect(self.Descargar_FDSN_2)                   # Call the function to run Module 10 (ModIris_2)

        self.pushButton_12.clicked.connect(self.Exit)                               # Call the function to exit system (Exit)



    """ ------------- Start of Program Functions  ------------ """

    def Analysis1(self):   # Call function to Analysis_System_1 Module 1.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Analysis_System_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Analysis_System_1.py"])
            app.quit()


    def STA_LTA(self):   # Call function to STA/LTA Module 2.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Sta_Lta_trigger_methods.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Sta_Lta_trigger_methods.py"])
            app.quit()


    def Ploting_24hrs(self):   # Call function to Sound_Wav. Module 3.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Days_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Days_1.py"])
            app.quit()

    def SonidoWav(self):   # Call function to 24 hrs. Module 4.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Sound_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Sound_1.py"])
            app.quit()

    def Integrales(self):   # Call function to Integrales. Module 5.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Integrals_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Integrals_1.py"])
            app.quit()


    def Cortar(self):   # Call function to Cut and save records. Module 6.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Cut_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Cut_1.py"])
            app.quit()


    def Fusionar(self):   # Call function to merge and save records. Module 7.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Merge_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Merge_1.py"])
            app.quit()

    def Convertir(self):   # Call function to Save events from a MSEED and SAC format. Module 8.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Convert_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Convert_1.py"])
            app.quit()

    def Descargar_FDSN(self):   # Call function to Download Seismic Records from the FDSN network. Module 9.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "Download_FDSN_1.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "Download_FDSN_1.py"])
            app.quit()

    def Descargar_FDSN_2(self):   # Call function to Download Individual Seismic Data Download from the FDSN network. Module 10.
        if System1 == "Windows":                                                    # In case it's Windows
            subprocess.Popen(["python", "ModIris_2.py"])
            app.quit()

        else:                                                                       # In case it's Linux
            subprocess.Popen(["python3", "ModIris_2.py"])
            app.quit()


    """  Fuction to exit system  """

    def Exit(self):    # Function to show exit dialog box
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Exit System")
        msg.setText("Are you sure to exit the System?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                        # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                           # If the answer is OK
            app.closeAllWindows()                                                   # Close all windows
            app.quit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
