# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System - > Merge Records Event

# Andalusian Institute of Geophysics
# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Granada University, (Ugr), Spain, 2021 - 2023

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 7 - Merge_1.py -> System to select, merge and save events since seismic records

# Part of the comments are written, both in English and in Castilian (Spanish).


# Load libraries to use

# For system use, threads and paths (path)
import sys
import os
import subprocess
from pathlib import Path

import warnings  # librería para alertas

# Libraries for graphics using matplotlib and using numpy, plotly
import numpy as np
from numpy import arange, array
from matplotlib import pyplot
from matplotlib.widgets import SpanSelector, MultiCursor

# Libraries for the use of PyQt5 - binding of the graphical Qt library
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton
from PyQt5.QtCore import QCoreApplication
from PyQt5.QtWidgets import *
import sys

from PyQt5 import QtGui

# Identify the operating system
import platform
sistema = platform.system()  # Identify the operating system

# Libraries to use tkinter (Graphical interface)
import tkinter
import tkinter as tk
from tkinter.ttk import Combobox, Style
from tkinter.messagebox import showerror, showinfo, askyesno
from tkinter import Frame, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT

# En caso de utilizar la ventana como root (cambios a posteriori)
from tkinter import *
root = tk.Tk()

root.iconphoto(False, tk.PhotoImage(file="Images/Ugr.gif"))

root.withdraw()

from os.path import join as os_path_join
from os.path import dirname as os_path_dirname

# import matplotlib.cbook as cbook
import numpy as np
from numpy import arange, array
from matplotlib import pyplot
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from matplotlib.widgets import SpanSelector, MultiCursor

# To read records through the "obspy" library
import obspy
from obspy.imaging.cm import obspy_sequential
from obspy.signal.tf_misfit import cwt
from obspy import Stream
from obspy import read
from obspy.io.sac import SACTrace
from obspy import read, Trace

from obspy.core import UTCDateTime, Stream, Trace, read, AttribDict
from obspy.core.util import NamedTemporaryFile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(r"Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Set frame group 2

        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 701, 271))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")


        """ --- Values for Text Labels (Label) Frame 2 --- """

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(260, 40, 431, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(208, 254, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_4.setPalette(palette)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(270, 20, 201, 16))
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(190, 200, 221, 16))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(260, 130, 431, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(270, 110, 201, 16))
        self.label_8.setObjectName("label_8")

        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(180, 220, 511, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 224, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 224, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 224, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 224, 245))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_11.setPalette(palette)
        self.label_11.setAutoFillBackground(True)
        self.label_11.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")

        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(160, 30, 81, 20))
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(170, 50, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")

        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(160, 110, 81, 20))
        self.label_18.setObjectName("label_18")

        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(170, 130, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        """ --- Values for the separation lines on the canvas (line) Frame 2 --- """

        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(235, 0, 25, 190))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(10, 90, 691, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_9 = QtWidgets.QFrame(self.frame_2)
        self.line_9.setGeometry(QtCore.QRect(150, 0, 16, 271))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.line_13 = QtWidgets.QFrame(self.frame_2)
        self.line_13.setGeometry(QtCore.QRect(0, 0, 5, 271))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")

        self.line_15 = QtWidgets.QFrame(self.frame_2)
        self.line_15.setGeometry(QtCore.QRect(1, 0, 698, 2))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")

        self.line_16 = QtWidgets.QFrame(self.frame_2)
        self.line_16.setGeometry(QtCore.QRect(10, 180, 691, 20))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")


        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 101, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Load.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 210, 141, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/save_dir.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 130, 101, 41))
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")

        """ --- Values for Text Boxes (lineEdit) Frame 2 --- """

        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 70, 41, 21))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 150, 41, 21))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")



        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 120, 211, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # Set frame group 4

        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 701, 91))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_4.setPalette(palette)
        self.frame_4.setAutoFillBackground(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")

        self.line_14 = QtWidgets.QFrame(self.frame_4)
        self.line_14.setGeometry(QtCore.QRect(800, 0, 20, 121))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")

        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(700, 10, 71, 61))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(r"Images/Ugr.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(580, 30, 111, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/Plot.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setObjectName("pushButton_8")

        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 30, 101, 41))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Clean.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")

        self.line_4 = QtWidgets.QFrame(self.frame_4)
        self.line_4.setGeometry(QtCore.QRect(410, 0, 20, 91))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_6 = QtWidgets.QFrame(self.frame_4)
        self.line_6.setGeometry(QtCore.QRect(560, 0, 20, 91))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_12 = QtWidgets.QFrame(self.frame_4)
        self.line_12.setGeometry(QtCore.QRect(0, 80, 701, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")

        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(40, 10, 181, 61))
        self.label_10.setObjectName("label_10")

        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 101, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.line_8 = QtWidgets.QFrame(self.frame_4)
        self.line_8.setGeometry(QtCore.QRect(240, 0, 20, 91))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        # Set frame group 3

        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 430, 701, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(800, 0, 16, 61))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(590, 20, 101, 41))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon5)
        self.pushButton_7.setObjectName("pushButton_7")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 20, 101, 41))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/Back.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setObjectName("pushButton_6")

        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(140, 0, 20, 71))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_11 = QtWidgets.QFrame(self.frame_3)
        self.line_11.setGeometry(QtCore.QRect(560, 0, 20, 71))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(270, 10, 271, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Logodepto.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(180, 10, 71, 51))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/Ugr.gif"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 100, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Command Buttons
        self.pushButton.setStyleSheet("background-color: honeydew; color: blue")            # Text and Color of the Command Button (load File 1)
        self.pushButton_2.setStyleSheet("background-color: honeydew; color: blue")          # Text and Color of the Command Button (clean input)
        self.pushButton_3.setStyleSheet("background-color: silver; color: blue")            # Text and Color of the Command Button (Save Dir merge record)
        self.pushButton_4.setStyleSheet("background-color: honeydew; color: blue")          # Text and Color of the Command Button (load File 2)
        self.pushButton_6.setStyleSheet("background-color: CornflowerBlue; color: white")   # Text and Color of the Command Button (Go Back)
        self.pushButton_7.setStyleSheet("background-color: burlywood; color: blue")         # Text and Color of the Command Button (Exit)
        self.pushButton_8.setStyleSheet("background-color: gold; color: blue")              # Text and Color of the Command Button (Plot and save merge Signal)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Merge seismic Records - University of Granada (Ugr)"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#142cc8;\">Seismic Record 1- Path to Upload</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#142cc8;\">Merge Seismic Record  - Path to Save</span></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Save directory"))
        self.pushButton_3.setText(_translate("MainWindow", "Save Dir merge Record"))
        self.pushButton.setToolTip(_translate("MainWindow", "Load Record 1"))
        self.pushButton.setText(_translate("MainWindow", " Load Record 1"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Load Record 2"))
        self.pushButton_4.setText(_translate("MainWindow", " Load Record 2"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#142cc8;\">Seismic Record 2- Path to Upload</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; color:#610000;\">Trace number st(n):</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; font-style:italic; color:#00007f;\">By default: st(0)</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; color:#610000;\">Trace number st(n):</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt; font-weight:600; font-style:italic; color:#00007f;\">By default: st(0)</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#aa0000;\">Load files and paths - save records:</span></p></body></html>"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "Plot Record"))
        self.pushButton_8.setText(_translate("MainWindow", " Plot/Save merge"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "Clean Inputs"))
        self.pushButton_2.setText(_translate("MainWindow", " Clean Inputs"))
        self.label_10.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Warning</span><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">: </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-style:italic;\">Make sure that the upload directories </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-style:italic;\">and storage are selected.</span></p></body></html>"))


        self.pushButton_7.setText(_translate("MainWindow", " Exit"))
        self.pushButton_6.setText(_translate("MainWindow", " Go Back"))

        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Go Back</span></p></body></html>"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Exit System</span></p></body></html>"))

        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#0000ff;\">Concatenate seismic records. </span></p></body></html>"))

        # El valor (1,999) Indica que se van a utilizar solo hasta 4 posiciones de enteros
        self.lineEdit_5.setValidator(QtGui.QIntValidator(1, 999))        # Solo acepta números enteros en la caja de texto de número de traza_1. Valor dos digitos
        self.lineEdit_6.setValidator(QtGui.QIntValidator(1, 999))        # Solo acepta números enteros en la caja de texto de número de traza_2. Valor dos digitos

        # Enable and Disable text boxes initially
        self.lineEdit_5.setEnabled(True)                                # Enable Trace_1 No. st[0] Text box.
        self.lineEdit_6.setEnabled(True)                                # Enable Trace_2 No. st[0] Text box.

        self.lineEdit_5.setText("0")                                    # Inicia contenido de caja de texto de Nº de Traza_1 st[0].
        self.lineEdit_6.setText("0")                                    # Inicia contenido de caja de texto de Nº de Traza_2 st[0].

        # Command button actions, function calls
        self.pushButton.clicked.connect(self.abrir_archivo1)            # Call the function to upload file (Load File 1).
        self.pushButton_2.clicked.connect(self.limpiar_entradas)        # Calls the function to clean entries (Clean Entries).
        self.pushButton_3.clicked.connect(self.guardar)                 # Calls the function to save file (Save dir cut file).
        self.pushButton_4.clicked.connect(self.abrir_archivo2)          # Call the function to upload file (Load File 2).
        self.pushButton_6.clicked.connect(self.abrir_programa1)         # Call the function to return to the Home Screen (Go Back).
        self.pushButton_7.clicked.connect(self.Exit1)                   # Call the function to exit the System (Exit System).
        self.pushButton_8.clicked.connect(self.verificar2)              # Call the function to graph and the filter records (Filter).

    """ ------------- Start of Program Functions  ------------ """

    """ Function to open and clean """


    def abrir_archivo1(self):                               # Function, to search and load the records 1 according to the format

            if sistema == "Windows":
                self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta = Path(self.archivo_abierto)
                self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_4.setFont(font)                                      # Printing using text format.
                self.label_4.setText(self.archivo_abierto)                      # Printing on the file path label.

            else:
                self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta = Path(self.archivo_abierto)
                self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_4.setFont(font)                                      # Printing using text format.
                self.label_4.setText(self.archivo_abierto)                      # Printing on the file path label.



    def abrir_archivo2(self):                               # Function, to search and load the records 2 according to the format

            if sistema == "Windows":
                self.archivo_abierto2=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta3 = Path(self.archivo_abierto2)
                self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_7.setFont(font)                                      # Printing using text format.
                self.label_7.setText(self.archivo_abierto2)                      # Printing on the file path label.

            else:
                self.archivo_abierto2=filedialog.askopenfilename(initialdir = "/",
                    title = "Please, select file",filetypes = (("All Files","*.*"),
                    ("SAC Files","*.sac"),
                    ('MSEED Files','*.mseed'),
                    ('GSE2 Files','*.gse2'),
                    ('WAV Files','*.wav'),
                    ('Kinemetrics Files','*.evt')))

                self.ruta3 = Path(self.archivo_abierto2)
                self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()

                font=QtGui.QFont()
                font.setFamily("Times New Roman")
                font.setPointSize(8)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(60)
                self.label_7.setFont(font)                                      # Printing using text format.
                self.label_7.setText(self.archivo_abierto2)                      # Printing on the file path label.


    def guardar(self):                                                      # Función para búsqueda de registro de acuerdo al formato
        if sistema == "Windows":
            #print("Sistema Windows")
            self.archivo_abierto3=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta5 = Path(self.archivo_abierto3)
            self.ruta6 = self.ruta5.joinpath(self.ruta5).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_11.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_11.setText(self.archivo_abierto3 + "/")               # Impresión en la eiqueta de la ruta del fichero

        else:                                                               # If the system is Linux
            self.archivo_abierto3=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta5 = Path(self.archivo_abierto3)
            self.ruta6 = self.ruta5.joinpath(self.ruta5).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_11.setFont(font)                                 # Impresion mediante el formato de texto
            self.label_11.setText(self.archivo_abierto3 + "/")          # Impresión en la eiqueta de la ruta del fichero


    def limpiar_entradas(self):                                         # Dejar todo como al inicio

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Clean all inputs.")
        msg.setText("Are you sure to delete all entries?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                    # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                       # If the answer is OK

            # Cierra graficos existentes
            plt.close()

            # Limpiar entradas Etiquetas y cajas de texto
            self.label_4.setText("")                                        # Borra contenido etiqueta de Ruta de Archivo 1
            self.label_7.setText("")                                        # Borra contenido etiqueta de Ruta de Archivo 2
            self.label_11.setText("")                                       # Borra contenido etiqueta de Ruta de Directorio a Guardar Archivo Final

            # Enable and Disable text boxes initially
            self.lineEdit_5.setEnabled(True)                                # Enable Trace_1 No. st[0] Text box.
            self.lineEdit_6.setEnabled(True)                                # Enable Trace_2 No. st[0] Text box.

            self.lineEdit_5.setText("0")                                    # Inicia contenido de caja de texto de Nº de Traza_1 st[0].
            self.lineEdit_6.setText("0")                                    # Inicia contenido de caja de texto de Nº de Traza_2 st[0].

            plt.close()                                                     # cierra el gráfico existente

        else:
            pass


    def verificar2(self):                                    # Función para validar entradas y graficar la fusión de los registros

            try:
                # Verificación y validación de que las entradas no estén vacías
                if not self.lineEdit_5.text():
                    MensCombo1 = QMessageBox()
                    MensCombo1.setIcon(QMessageBox.Warning)
                    MensCombo1.setWindowTitle("Trace 1 No. Empty")
                    MensCombo1.setText("Please, enter a valid Value")
                    returnValue = MensCombo1.exec()

                elif not self.lineEdit_6.text():
                    MensCombo2 = QMessageBox()
                    MensCombo2.setIcon(QMessageBox.Warning)
                    MensCombo2.setWindowTitle("Trace 2 No. Empty")
                    MensCombo2.setText("Please, enter a valid Value")
                    returnValue = MensCombo2.exec()

                elif not self.label_4.text():
                    MensCombo3 = QMessageBox()
                    MensCombo3.setIcon(QMessageBox.Warning)
                    MensCombo3.setWindowTitle("Path and file 1 name Empty")
                    MensCombo3.setText("Please, enter a valid Value")
                    returnValue = MensCombo3.exec()

                elif not self.label_7.text():
                    MensCombo4 = QMessageBox()
                    MensCombo4.setIcon(QMessageBox.Warning)
                    MensCombo4.setWindowTitle("Path and file 2 name Empty")
                    MensCombo4.setText("Please, enter a valid Value")
                    returnValue = MensCombo4.exec()

                elif not self.label_11.text():
                    MensCombo5 = QMessageBox()
                    MensCombo5.setIcon(QMessageBox.Warning)
                    MensCombo5.setWindowTitle("Path and Directory Empty")
                    MensCombo5.setText("Please, enter a valid Value")
                    returnValue = MensCombo5.exec()

                else:

                    plt.close()                                                 # Close the existing chart.

                    archivoFil1 = (self.label_4.text())                         # Lectura etiqueta del Record 1
                    archivoFil2 = (self.label_7.text())                         # Lectura etiqueta del Record 2
                    archivoFil3 = (self.label_11.text())                         # Lectura etiqueta del Directorio

                    # Para carpar el camino del fichero y colocarlo en el nombre del fichero final
                    head, tail = os.path.split(self.archivo_abierto)
                    root, extension = os.path.splitext(tail)

                    # Lectura de los registros
                    st  = obspy.read(archivoFil1)                                # Lectura archivo de acuerdo al formato
                    st  += obspy.read(archivoFil2)                               # Lectura archivo de acuerdo al formato

                    # sort
                    st.sort(['starttime'])

                    # Para realizar una copia del registro principal
                    st2 = st.copy()
                    tr2 = st.select()[1]

                    # use common reference time and have x-Axis as relative time in seconds.
                    # Another option would be to plot absolute times by using
                    # Trace.times(type='matplotlib') and letting matplotlib know that x-Axis has
                    # absolute times, by using ax.xaxis_date() and fig.autofmt_xdate()
                    t0 = st[0].stats.starttime

                    # Go through the stream object and plot the data with a shared x axis
                    fig, axes = plt.subplots(nrows=len(st)+1, sharex=True)

                    ax = None

                    for (tr, ax) in zip(st, axes):
                        ax.plot(tr.times(reftime=t0), tr.data)


                    # Merge the data together and plot in a similar way in the bottom Axes. Use method 1
                    st.merge(method=1)
                    axes[-1].plot(st[0].times(reftime=t0), st[0].data, 'k')     # [0] grafico superior, [1] grafico enmedio,  [-1] grafico inferior
                    axes[0].set_title(f"Record 1 : {t0} ", color ="red")
                    axes[1].set_title("Record 2 : %s " % tr.stats.starttime, color ="darkgreen")
                    axes[0].grid()
                    axes[1].grid()

                    axes[-1].set_title("Recod Merge ", color ="blue")
                    axes[-1].set_xlabel(f'Time[s] relative to {t0}')
                    plt.grid()
                    plt.show()

                    #= Ventana de dialogo (MessageBox) para guardar el corte por formatos SAC y MSEED
                    dialog = QMessageBox()
                    dialog.setWindowTitle("Save the event cut Record")
                    dialog.setText("Do you want to save MSEED or SAC Format?, CANCEL = Close all graphics")
                    # Se introducen los botones de comandos de acción personalizados y su ejecución
                    dialog.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel | QMessageBox.No)
                    dialog.button(QMessageBox.Ok).setText("MSEED")
                    dialog.button(QMessageBox.Cancel).setText("CANCEL")
                    dialog.button(QMessageBox.No).setText("SAC")
                    # Se configura un icono para el mensaje
                    dialog.setIcon(QMessageBox.Question)

                    # Se ejecuta el dialogo y se captura la respuesta obtenida
                    returnValue = dialog.exec_()
                    # Se comprueba que tipo de botón de comando se ha ejecutado
                    if returnValue == QMessageBox.Ok:       # Si el valor es OK, se ejecuta guardar MSEED
                        F1 = (root + '.MSEED')
                        F2 = (archivoFil3 + F1)
                        st[0].write( filename= (F2), format="MSEED")

                        showinfo(title = "File MSEED successfully created", message = "Successfully created record.\n\n")
                        plt.close()
                        #print("Formato MSEED")
                    elif returnValue == QMessageBox.No:     # Si el valor es NO, se ejecuta guardar SAC
                        F3 = (root + '.SAC')
                        F4 = (archivoFil3 + F3)
                        st[0].write( filename= (F4), format="SAC")
                        showinfo(title = "File SAC successfully created", message = "Successfully created record.\n\n")
                        plt.close()
                        #print('Formato SAC')
                    else:                                   # Otro caso, se ejecuta CANCEL y se cierra la ventana de gráficos
                        showinfo(title = "Close all graphics", message = "The plot windows close.\n\n")
                        plt.close()


            except:                                         # En caso de existin algún error con los registros se presenta la ventana de dialogo
                plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setWindowTitle("Save the event cut Record")
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")
                msgBox.setWindowTitle("Invalid Record File")
                returnValue = msgBox.exec()
                pass


    """ Function to go back at home """

    def abrir_programa1(self):                                              # Call function to another program (Back)
        if sistema == "Windows":                                            # If the system is Windows
            plt.close()                                                     # Close the existing chart.
            subprocess.Popen(["python", "Menu.py"])                        # Open de Index program
            app.quit()
        else:                                                               # If the system is Linux or Mac
            plt.close()                                                     # Close the existing chart
            subprocess.Popen(["python3", "Menu.py"])                       # Open de Index program
            app.quit()


    """  Fuction to exit system  """

    def Exit1(self):                                                        # Call function to show exit dialog box

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Exit System")
        msg.setText("Are you sure to exit the System?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                   # If the answer is OK
            app.closeAllWindows()                                           # Close all windows


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
