# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System / Individual Seismic Data Download from the FDSN network

# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Andalusian Institute of Geophysics.
# Granada University, (Ugr), Spain, 2021 - 2023

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 9 - ModIris_2.py -> Individual Seismic Data Download from the FDSN network

# Interface, for Download Seismic Records from the FDSN network.


# Load libraries to use

import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets
#from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5.QtCore import  QSize

from datetime import date
from datetime import datetime


from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QMessageBox, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon

# Cargar y ver el sistema operativo que se maneja
import platform
sistema = platform.system()

# Libraries to use tkinter (Graphical interface)
import tkinter
from tkinter import *
import tkinter as tk
#from tkinter.messagebox import showerror, showinfo, askyesno
from tkinter import Frame, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT
root = tk.Tk()
root.withdraw()

# For system use, threads and paths
import sys
import subprocess
from pathlib import Path

# Para las librerías de obspy
from obspy.core import UTCDateTime
from obspy.clients.fdsn import Client
import obspy.io.mseed


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        #MainWindow.resize(829, 374)
        MainWindow.setFixedSize(829, 374) # Impide que cambie de tamaño, setFixedSize(int, int)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        #MainWindow.setSizeGripEnabled(True)
        #MainWindow.setModal(False)

        self.frame_2 = QtWidgets.QFrame(MainWindow)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 811, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(30, 50, 101, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton.setPalette(palette)
        self.pushButton.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Store.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 315, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(300, 0, 20, 141))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(660, 0, 20, 141))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setGeometry(QtCore.QRect(140, 0, 20, 141))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.line_11 = QtWidgets.QFrame(self.frame_2)
        self.line_11.setGeometry(QtCore.QRect(800, 0, 20, 141))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")

        self.line_12 = QtWidgets.QFrame(self.frame_2)
        self.line_12.setGeometry(QtCore.QRect(310, 60, 361, 20))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")

        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(160, 10, 131, 121))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Images/UGR6.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.line_6 = QtWidgets.QFrame(self.frame_2)
        self.line_6.setGeometry(QtCore.QRect(480, 70, 20, 71))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 40, 101, 51))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Clean.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(340, 40, 121, 16))
        self.label_9.setObjectName("label_9")

        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(520, 40, 121, 16))
        self.label_11.setObjectName("label_11")

        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(320, 85, 151, 31))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(500, 85, 151, 31))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label_44 = QtWidgets.QLabel(self.frame_2)
        self.label_44.setGeometry(QtCore.QRect(322, 120, 148, 21))
        self.label_44.setObjectName("label_44")

        self.label_45 = QtWidgets.QLabel(self.frame_2)
        self.label_45.setGeometry(QtCore.QRect(507, 120, 148, 21))
        self.label_45.setObjectName("label_45")

        self.frame_3 = QtWidgets.QFrame(MainWindow)
        self.frame_3.setGeometry(QtCore.QRect(10, 300, 811, 61))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 481, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        self.label_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(160, 0, 151, 21))
        self.label.setObjectName("label")

        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(150, 0, 3, 61))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(660, 0, 3, 61))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(800, 0, 16, 61))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(680, 10, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 10, 101, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.pushButton_4.setPalette(palette)
        self.pushButton_4.setAutoFillBackground(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Back.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")

        self.frame = QtWidgets.QFrame(MainWindow)
        self.frame.setGeometry(QtCore.QRect(10, 160, 811, 101))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(50, 70, 71, 21))
        self.label_21.setObjectName("label_21")

        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(60, 10, 41, 21))
        self.label_17.setObjectName("label_17")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 40, 91, 21))
        self.lineEdit_3.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(210, 40, 71, 21))
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.label_43 = QtWidgets.QLabel(self.frame)
        self.label_43.setGeometry(QtCore.QRect(220, 10, 51, 21))
        self.label_43.setObjectName("label_43")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(410, 20, 71, 21))
        self.lineEdit_5.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.label_49 = QtWidgets.QLabel(self.frame)
        self.label_49.setGeometry(QtCore.QRect(337, 74, 180, 21))
        self.label_49.setObjectName("label_49")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(410, 50, 71, 21))
        self.lineEdit_6.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.label_35 = QtWidgets.QLabel(self.frame)
        self.label_35.setGeometry(QtCore.QRect(360, 20, 51, 21))
        self.label_35.setObjectName("label_35")

        self.label_50 = QtWidgets.QLabel(self.frame)
        self.label_50.setGeometry(QtCore.QRect(360, 50, 51, 21))
        self.label_50.setObjectName("label_50")

        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 30, 101, 51))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/Lupa3.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setObjectName("pushButton_3")

        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(540, 10, 101, 81))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")

        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setGeometry(QtCore.QRect(510, 0, 20, 101))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")

        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setGeometry(QtCore.QRect(160, 0, 20, 101))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")

        self.line_17 = QtWidgets.QFrame(self.frame)
        self.line_17.setGeometry(QtCore.QRect(320, 0, 20, 101))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")

        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setGeometry(QtCore.QRect(660, 0, 20, 101))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")

        self.line_8 = QtWidgets.QFrame(MainWindow)
        self.line_8.setGeometry(QtCore.QRect(10, 260, 251, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.line_9 = QtWidgets.QFrame(MainWindow)
        self.line_9.setGeometry(QtCore.QRect(10, 280, 811, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.label_8 = QtWidgets.QLabel(MainWindow)
        self.label_8.setGeometry(QtCore.QRect(270, 260, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.line_13 = QtWidgets.QFrame(MainWindow)
        self.line_13.setGeometry(QtCore.QRect(560, 260, 261, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")

        self.line_14 = QtWidgets.QFrame(MainWindow)
        self.line_14.setGeometry(QtCore.QRect(0, 10, 20, 141))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Command Buttons
        self.pushButton.setStyleSheet("background-color: honeydew; color: blue")                # Text and Color of the Command Button (Path/Save)
        self.pushButton_2.setStyleSheet("background-color: bisque; color: blue")                # Text and Color of the Command Button (clean inputs)
        self.pushButton_3.setStyleSheet("background-color: lightblue; color: black")            # Text and Color of the Command Button (Search)
        #self.pushButton_4.setStyleSheet("background-color: honeydew; color: blue")             # Text and Color of the Command Button (load File 2)
        self.pushButton_4.setStyleSheet("background-color: CornflowerBlue; color: white")       # Text and Color of the Command Button (Go Back)
        self.pushButton_5.setStyleSheet("background-color: tan; color: blue")                   # Text and Color of the Command Button (Exit)

        # Disable text boxes again as at startup
        self.pushButton_3.setEnabled(False)                                 # Disable the SEARCH command
        self.lineEdit.setEnabled(False)                                     # Disable the UTCDateTime : Startime text box.
        self.lineEdit_2.setEnabled(False)                                   # Disable the UTCDateTime : Endtime text box.
        self.lineEdit_3.setEnabled(False)                                   # Disable the Client text box.
        self.lineEdit_4.setEnabled(False)                                   # Disable the Network text box.
        self.lineEdit_5.setEnabled(False)                                   # Disable the Station text box.
        self.lineEdit_6.setEnabled(False)                                   # Disable the Channel text box.

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        # Texto en la barra de título y en las etiquetas
        MainWindow.setWindowTitle(_translate("MainWindow", "Individual Seismic Data Download from the FDSN Network - Granada University (Ugr)"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:630; color:#aa5500;\">Time Values: (Year, Month, Day, Hour, Minute, Second)</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Startime: "))
        self.label_11.setText(_translate("MainWindow", "Endtime: "))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;font-weight:600; color:#5555ff;\">e.g. Format: (2009, 4, 24, 8, 27, 12)</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;font-weight:600; color:#5555ff;\">e.g. Format: (2009, 4, 24, 8, 27, 12)</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:italic; color:#0000ff;\">Path to Save Records:</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">e.g. IRIS</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">Client</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">Network</span></p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;font-weight:600; color:#5555ff;\">Input \"*\" for all channel or e.g. BH?</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">Station</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">Channel</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#aa0000;\">Path to save records / Return and Exit Commands</span></p></body></html>"))

        # text message on the buttons
        self.pushButton.setText(_translate("MainWindow", " Path\n" " Save"))
        self.pushButton_2.setText(_translate("MainWindow", " Clean Inputs"))
        self.pushButton_3.setText(_translate("MainWindow", " Search"))
        self.pushButton_4.setText(_translate("MainWindow", "  Go Back"))
        self.pushButton_5.setText(_translate("MainWindow", "  Exit"))

        # "Tooltip" text message of the buttons
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">Directory to store the record:</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">Clean Inputs</span></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#00007f;\">Download Records</span></p></body></html>"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Back to Index</span></p></body></html>"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Exit System</span></p></body></html>"))

        # Acciones de los botones de comandos, llamadas a funciones
        self.pushButton.clicked.connect(self.Registro)                                      # Llama a la función para seleccionar el directorio de los Registros.
        self.pushButton_2.clicked.connect(self.limpiar_entradas)                            # Llama a la función para limpiar entradas (Limpiar Entradas)
        self.pushButton_3.clicked.connect(self.Buscar)                                      # Llama a la función para para descargar los registros (De acuerdo al Dominio)
        self.pushButton_4.clicked.connect(self.Regreso)                                     # Llama a la función para Regresar al Menu (Regreso)
        self.pushButton_5.clicked.connect(self.Salida)                                      # Llama a la función para Salir del Sistema (Salir)

    # *** --- Comienzo de las funciones del programa --- ***

    def Registro(self):                                                      # Función para búsqueda de registro de acuerdo al formato
        if sistema == "Windows":
            #print("Sistema Windows")
            self.activacion1()
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()
            #print("La extensión del Registro es: ", self.ruta4.suffix)

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_2.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_2.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

            # Activar el botón de comando de busquieda
            self.pushButton_3.setEnabled(True)                                # Enable the SEARCH command

        else:                                                               # If the system is Linux
            self.activacion1()
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()
            #print("La extensión del Registro es: ", self.ruta4.suffix)

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_2.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_2.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

            # Activar el botón de comando de busquieda
            self.pushButton_3.setEnabled(True)                                # Enable the SEARCH command

    def Buscar(self):

        try:

            # Validaciones de entrada de caja de datos
            # Verificar que las cajas de texto implicadas no estén vacías o entradas invalidas

            if not self.lineEdit.text():                                # Validacion de entrada de caja de texto de Startime
                    MensCombo1 = QMessageBox()
                    MensCombo1.setIcon(QMessageBox.Warning)
                    MensCombo1.setWindowTitle("Startime Value Empty")
                    MensCombo1.setText("Please, enter a valid Value")
                    returnValue = MensCombo1.exec()

            elif not self.lineEdit_2.text():                            # Validacion de entrada de caja de texto de Endtime
                    MensCombo2 = QMessageBox()
                    MensCombo2.setIcon(QMessageBox.Warning)
                    MensCombo2.setWindowTitle("Endtime Value Empty")
                    MensCombo2.setText("Please, enter a valid Value")
                    returnValue = MensCombo2.exec()

            elif not self.lineEdit_3.text():                            # Validacion de entrada de caja de texto de Client
                    MensCombo3 = QMessageBox()
                    MensCombo3.setIcon(QMessageBox.Warning)
                    MensCombo3.setWindowTitle("Client Value Empty")
                    MensCombo3.setText("Please, enter a valid Value")
                    returnValue = MensCombo3.exec()

            elif not self.lineEdit_4.text():                            # Validacion de entrada de caja de texto de Network
                    MensCombo4 = QMessageBox()
                    MensCombo4.setIcon(QMessageBox.Warning)
                    MensCombo4.setWindowTitle("Network Value Empty")
                    MensCombo4.setText("Please, enter a valid Value")
                    returnValue = MensCombo4.exec()

            elif not self.lineEdit_5.text():                            # Validacion de entrada de caja de texto de Station
                    MensCombo5 = QMessageBox()
                    MensCombo5.setIcon(QMessageBox.Warning)
                    MensCombo5.setWindowTitle("Station Value Empty")
                    MensCombo5.setText("Please, enter a valid Value")
                    returnValue = MensCombo5.exec()

            elif not self.lineEdit_6.text():                            # Validacion de entrada de caja de texto de Channel
                    MensCombo6 = QMessageBox()
                    MensCombo6.setIcon(QMessageBox.Warning)
                    MensCombo6.setWindowTitle("Channel Value Empty")
                    MensCombo6.setText("Please, enter a valid Value")
                    returnValue = MensCombo6.exec()

            elif not self.label_2.text():                               # Validacion de entrada de Path Record and Directory name
                    MensCombo7 = QMessageBox()
                    MensCombo7.setIcon(QMessageBox.Warning)
                    MensCombo7.setWindowTitle("Path and Directory name Empty")
                    MensCombo7.setText("Please, enter a valid Value")
                    returnValue = MensCombo7.exec()

            else:

                # Lectura etiqueta del Path and Directory name
                archivoFil1 = (self.label_2.text())

                #print('El registro y directorio es: ', archivoFil1)
                # Lectura de entradas de las cajas de texto
                Startime1 = (self.lineEdit.text())                              # Lectura etiqueta de entrada de caja de texto de Startime
                Endtime1 = (self.lineEdit_2.text())                             # Lectura etiqueta de entrada de caja de texto de Endtime
                Client1 = (self.lineEdit_3.text())                              # Lectura etiqueta de entrada de caja de texto de Client
                Network1 = (self.lineEdit_4.text())                             # Lectura etiqueta de entrada de caja de texto de Network
                Station1 = (self.lineEdit_5.text())                             # Lectura etiqueta de entrada de caja de texto de Station
                Channel1 = (self.lineEdit_6.text())                             # Lectura etiqueta de entrada de caja de texto de Channel

                client = Client(Client1)

                origin_time = obspy.UTCDateTime(Startime1)         # Convierte el valor a tiempo original UTC
                end_time = obspy.UTCDateTime(Endtime1)             # Convierte el valor a tiempo original UTC

                t=origin_time
                t2=end_time


                #= Ventana de dialogo (MessageBox) para guardar el corte por formatos SAC y MSEED
                dialog = QMessageBox()
                dialog.setWindowTitle("Save the event cut Record")
                dialog.setText("Do you want to save MSEED or SAC Format?, CANCEL = Close all graphics")
                # Se introducen los botones de comandos de acción personalizados y su ejecución
                dialog.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel | QMessageBox.No)
                dialog.button(QMessageBox.Ok).setText("MSEED")
                dialog.button(QMessageBox.Cancel).setText("CANCEL")
                dialog.button(QMessageBox.No).setText("SAC")
                # Se configura un icono para el mensaje
                dialog.setIcon(QMessageBox.Question)

                # Se ejecuta el dialogo y se captura la respuesta obtenida
                returnValue = dialog.exec_()
                # Se comprueba que tipo de botón de comando se ha ejecutado
                if returnValue == QMessageBox.Ok:       # Si el valor es OK, se ejecuta guardar MSEED

                    t=origin_time
                    t2=end_time

                    # Registro
                    raw_data = client.get_waveforms(
                        network=Network1,
                        station=Station1,
                        location='*',
                        channel=Channel1,   # Para todos los canales utilizar "*"
                        starttime=t,
                        endtime=t2,
                        attach_response=True)

                    '''To further download station information execute: '''

                    xml  = client.get_stations(network=Network1,station=Station1,
                    channel=Channel1,starttime=t,endtime=t2,level='response')

                    ''' 'To scale the data using the station’s meta-data: '''

                    data = raw_data.remove_response(inventory=xml)

                    ''' To filter, trim and plot the data execute: '''

                    head, tail = os.path.split(self.archivo_abierto2)

                    root, extension = os.path.splitext(tail)

                    # PARA OBTENER LOS VALORES DE LA FECHA DE ORIGEN
                    anio = origin_time.year
                    mes = origin_time.month
                    dia = origin_time.day
                    hora = origin_time.hour

                    # Asigna a F1, la Captura del nombre del registro y añade la extensión .MSEED
                    F1 = ('Record' '_' + Network1 + '_' + Station1 + '_' + str(anio) + '-' + str(mes) + '-' + str(dia) +  '.mseed')

                    # Asigna a F2 el directorio mas el nombre anterior donde se almacenará el registro
                    F2 = (archivoFil1 + F1)

                    # Escritura del fichero en formato MSEED
                    data.write(F2, format="MSEED")


                    # Caja de dialogo que muestra que el fichero .MSEED ha sido almacenado con éxito
                    #showinfo(title = "File MSEED successfully created", message = "Successfully created MSEED record.\n\n")
                    MensCombo8 = QMessageBox()
                    MensCombo8.setIcon(QMessageBox.Information)
                    MensCombo8.setWindowTitle("MSEED record file")
                    MensCombo8.setText("MSEED file created successfully")
                    returnValue = MensCombo8.exec()

                elif returnValue == QMessageBox.No:     # Si el valor es NO, se ejecuta guardar SAC

                    t=origin_time
                    t2=end_time

                    raw_data = client.get_waveforms(
                        network=Network1,
                        station=Station1,
                        location='*',
                        channel=Channel1,   # Para todos los canales utilizar "*"
                        starttime=t,
                        endtime=t2,
                        attach_response=True)

                    '''To further download station information execute: '''

                    xml  = client.get_stations(network=Network1,station=Station1,
                    channel=Channel1,starttime=t,endtime=t2,level='response')

                    ''' 'To scale the data using the station’s meta-data: '''

                    data = raw_data.remove_response(inventory=xml)

                    ''' To filter, trim and plot the data execute: '''

                    head, tail = os.path.split(self.archivo_abierto2)

                    root, extension = os.path.splitext(tail)

                    # PARA OBTENER LOS VALORES DE LA FECHA DE ORIGEN
                    anio = origin_time.year
                    mes = origin_time.month
                    dia = origin_time.day
                    hora = origin_time.hour

                    # Asigna a F1, la Captura del nombre del registro y añade la extensión .MSEED
                    F1 = ('Record' '_' + Network1 + '_' + Station1 + '_' + str(anio) + '-' + str(mes) + '-' + str(dia) +  '.sac')

                    # Asigna a F2 el directorio mas el nombre anterior donde se almacenará el registro
                    F2 = (archivoFil1 + F1)

                    # Escritura del fichero en formato MSEED
                    data.write(F2, format="SAC")


                    # Caja de dialogo que muestra que el fichero .MSEED ha sido almacenado con éxito
                    #showinfo(title = "File SAC successfully created", message = "Successfully created SAC record.\n\n")
                    MensCombo9 = QMessageBox()
                    MensCombo9.setIcon(QMessageBox.Information)
                    MensCombo9.setWindowTitle("SAC record file")
                    MensCombo9.setText("SAC file created successfully")
                    returnValue = MensCombo9.exec()
                else:                                   # Otro caso, se ejecuta CANCEL y se cierra la ventana de gráficos
                    pass
                        #showinfo(title = "Close this Windows", message = "The windows close.\n\n")

        except:                                         # Validacion de cualquier posibilidad de error, presenta una ventana de dialogo
                #plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setWindowTitle("Save the event cut Record")
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")
                msgBox.setWindowTitle("Invalid Record File")
                returnValue = msgBox.exec()
                pass

    def limpiar_entradas(self):                                             # Clean and leave everything as at the beginning.


        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Clean all inputs.")
        msg.setText("Are you sure to delete all entries?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                    # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                       # If the answer is OK

            # Delete label content and Text Boxes.
            self.label_2.setText("")                                            # Delete the contents of the File Path label
            self.lineEdit.setText("")                                           # Clear the content of the UTCDateTime : Startime.
            self.lineEdit_2.setText("")                                         # Clear the content of the UTCDateTime : Endtime.
            self.lineEdit_3.setText("")                                         # Clear the content of the Client.
            self.lineEdit_4.setText("")                                         # Clear the content of the Network.
            self.lineEdit_5.setText("")                                         # Clear the content of the Station.
            self.lineEdit_6.setText("")                                         # Clear the content of the Channel.

            # Disable text boxes again as at startup
            self.lineEdit.setEnabled(False)                                     # Disable the UTCDateTime : Startime text box.
            self.lineEdit_2.setEnabled(False)                                   # Disable the UTCDateTime : Endtime text box.
            self.lineEdit_3.setEnabled(False)                                   # Disable the Client text box.
            self.lineEdit_4.setEnabled(False)                                   # Disable the Network text box.
            self.lineEdit_5.setEnabled(False)                                   # Disable the Station text box.
            self.lineEdit_6.setEnabled(False)                                   # Disable the Channel text box.

            # Disable Search Command again as at starup
            self.pushButton_3.setEnabled(False)                                 # Disable the SEARCH command

        else:
            pass

    def activacion1(self):                                             # Clean and leave everything as at the beginning.

        # Delete label content and Text Boxes.
        #self.label_2.setText("")                                            # Delete the contents of the File Path label
        #self.lineEdit.setText("")                                           # Clear the content of the UTCDateTime : Startime.
        #self.lineEdit_2.setText("")                                         # Clear the content of the UTCDateTime : Endtime.
        #self.lineEdit_3.setText("")                                         # Clear the content of the Client.
        #self.lineEdit_4.setText("")                                         # Clear the content of the Network.
        #self.lineEdit_5.setText("")                                         # Clear the content of the Station.
        #self.lineEdit_6.setText("")                                         # Clear the content of the Channel.

        # Disable text boxes again as at startup
        self.lineEdit.setEnabled(True)                                     # Disable the UTCDateTime : Startime text box.
        self.lineEdit_2.setEnabled(True)                                   # Disable the UTCDateTime : Endtime text box.
        self.lineEdit_3.setEnabled(True)                                   # Disable the Client text box.
        self.lineEdit_4.setEnabled(True)                                   # Disable the Network text box.
        self.lineEdit_5.setEnabled(True)                                   # Disable the Station text box.
        self.lineEdit_6.setEnabled(True)                                   # Disable the Channel text box.


    def Regreso(self):                                                                      # Funcion de llamada a otro programa (Regresar)
        if sistema == "Windows":                                                            # Si el sistema es Windows
            subprocess.Popen(["python", "Menu.py"])
            app.quit()
            #print("Estamos en {}".format(sistema))
        else:                                                                               # Si el sistema es Linux
            #plt.close()  # cierra el gráfico existente
            subprocess.Popen(["python3", "Menu.py"])
            app.quit()

    def Salida(self):                                                                       # Funcion para mostrar caja de dialogo de salida
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("System Output")
        msg.setText("Are you sure to exit the system?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                                # Por Defecto el foco esta en el boton OK
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                                   # Si la respuesta es SI
            app.closeAllWindows()                                                           # Cierra todas las ventanas


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
