# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.2 and modified by later code editing
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# Developed by: Ligdamis A. Gutiérrez E. PhD.
# Seismic Analysis System - > Coverting Seismic Records to Wav sound

# Andalusian Institute of Geophysics
# Department of Theoretical Physics and the Cosmos,
# Science Faculty,
# Granada University, (Ugr), Spain, 2021 - 2022

''' WARNING: Do not modify or edit the code without permission of the author.
    In case of using this software, indicate and refer to the author and the institution he represents.
    The University of Granada, Ugr '''

# Program: Module 4 - Sound_1.py -> Coverting Seismic Records to Wav sound

# Part of the comments are written, both in English and in Castilian (Spanish).


# Load libraries to use

import sys
import os
import subprocess
from PyQt5.QtWidgets import QApplication, QWidget, QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets

# Load and see the operating system to use
import platform
sistema = platform.system()

from PyQt5 import QtCore, QtGui, QtWidgets

# For sound libraries
import pyaudio
import wave

# For system use, threads and paths
import sys
import subprocess
from pathlib import Path

# To read records through the "obspy" library
import obspy
from obspy.imaging.cm import obspy_sequential
from obspy.signal.tf_misfit import cwt

# Libraries to use tkinter (Graphical interface)
import tkinter
import tkinter as tk
from tkinter.ttk import Combobox, Style
from tkinter import Frame, IntVar, Label, filedialog, Entry, Radiobutton, CURRENT
# En caso de utilizar la ventana como root (cambios a posteriori)
from tkinter import *
root = tk.Tk()
root.withdraw()

# Import matplotlib.cbook as cbook
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

from scipy.io import wavfile
from scipy import fft, arange

import numpy as np
import scipy.io.wavfile as waves


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 554)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Ugr.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Set frame group 1

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 60, 701, 161))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(216, 225, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 101, 41))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(r"Images/Load.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")         # Button to upload file (Search Record)

        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 100, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(r"Images/Clean.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon7)

        """ --- Values for Text Labels (Label) Frame 1 --- """

        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 10, 71, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/Ugr.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(170, 0, 16, 161))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 171, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(340, 0, 16, 161))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        """ --- Values for Command Buttom (PushButton) Frame 1 --- """

        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 100, 101, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(r"Images/Store.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon4)

        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 20, 101, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(r"Images/Sound.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)

        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 100, 101, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(r"Images/Listen.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon8)

        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(560, 20, 101, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(r"Images/Plot.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon6)

        """ --- Values for the separation lines on the canvas (line) Frame 1 --- """

        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(510, 0, 16, 161))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setGeometry(QtCore.QRect(350, 70, 171, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setGeometry(QtCore.QRect(520, 70, 181, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(180, 70, 171, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.lineEdit = QtWidgets.QLineEdit(self.frame)                         # Frecuency Text box.
        self.lineEdit.setGeometry(QtCore.QRect(190, 130, 51, 20))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
         # Qt.ImhFormattedNumbersOnly       It only allows the use of numbers including decimals and a "-" sign.
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        rx1  = QtCore.QRegExp("[0-9]{999}")      # Format to only allow 2 integers
        val1 = QtGui.QRegExpValidator(rx1)
        self.lineEdit.setValidator(val1)
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)                       # Trace No. st[0] Text box.
        self.lineEdit_2.setGeometry(QtCore.QRect(285, 130, 51, 20))
        # Qt.ImhFormattedNumbers            It only allows the use of numbers including decimals and a "-" sign.
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        rx2  = QtCore.QRegExp("[0-9]{999}")      # Format to only allow 2 integers
        val2 = QtGui.QRegExpValidator(rx2)
        self.lineEdit_2.setValidator(val2)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(190, 90, 141, 16))
        self.label_9.setObjectName("label_9")

        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(180, 110, 141, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(240, 90, 141, 16))
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(240, 110, 141, 16))
        self.label_13.setObjectName("label_13")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(290, 5, 271, 51))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("Images/Logodepto.gif"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")

        # Set frame group 2

        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(10, 250, 701, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 641, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_4.setPalette(palette)
        self.label_4.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 151, 16))
        self.label_5.setObjectName("label_5")

        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setGeometry(QtCore.QRect(0, 90, 701, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")

        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 151, 16))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(30, 140, 641, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 245, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_7.setPalette(palette)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 230, 201, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # Set frame group 3

        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 460, 701, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 254, 219))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")

        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 20, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(r"Images/Back.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")     # Boton para Regresar a la pantalla de Inicio

        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setGeometry(QtCore.QRect(570, 20, 101, 41))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(r"Images/Exit.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setObjectName("pushButton_7")

        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(440, 10, 91, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Images/IAG.gif"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")

        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(170, 0, 241, 71))
        self.label_10.setObjectName("label_10")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Color and text formatting on Command Buttons
        self.pushButton.setStyleSheet("background-color: honeydew; color: blue")                # Button color and text color (Load File)
        self.pushButton_2.setStyleSheet("background-color: lightyellow; color: blue")           # Button color and text color (Clean Inputs)
        self.pushButton_3.setStyleSheet("background-color: silver; color: blue")                # Button color and text color (Path to Save the file)
        self.pushButton_4.setStyleSheet("background-color: wheat; color: blue")                 # Button color and text color (Coverting Wav file)
        self.pushButton_5.setStyleSheet("background-color: mistyrose; color: blue")             # Button color and text color (Listening the Wav file)
        self.pushButton_6.setStyleSheet("background-color: CornflowerBlue; color: white")       # Button color and text color (Back to Menu)
        self.pushButton_7.setStyleSheet("background-color: burlywood; color: blue")             # Button color and text color (Exit System)
        self.pushButton_8.setStyleSheet("background-color: gold; color: blue")                  # Button color and text color (Plot the file)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coverting Seismic Records to Wav sound - University of Granada (Ugr)"))

        self.pushButton.setText(_translate("MainWindow", " Load File"))
        self.pushButton_2.setText(_translate("MainWindow", " Clean Inputs"))
        self.pushButton_3.setText(_translate("MainWindow", " Save File"))
        self.pushButton_4.setText(_translate("MainWindow", " Create wav"))
        self.pushButton_5.setText(_translate("MainWindow", " Listen Wav"))
        self.pushButton_6.setText(_translate("MainWindow", " Back"))
        self.pushButton_7.setText(_translate("MainWindow", " Exit"))
        self.pushButton_8.setText(_translate("MainWindow", " Plot File"))

        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#142cc8;\">Directory and record to upload:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#142cc8;\">Directory to store the record:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-style:italic; color:#c80c28;\">Loading paths and storing records:</span></p></body></html>"))


        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Load File</span></p></body></html>"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Clean Inputs</span></p></body></html>"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Path Save file</span></p></body></html>"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Coverting Wav file</span></p></body></html>"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Listening Wav file</span></p></body></html>"))
        self.pushButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Go Back</span></p></body></html>"))
        self.pushButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#94181e;\">Exit</span></p></body></html>"))
        self.pushButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5500ff;\">Plot the file</span></p></body></html>"))


        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-style:italic; color:#1d20c8;\">Converting Records to Wav File</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"font-family:\'Times New Roman\'; font-size:7pt; font-weight:520; color:#aa0000;\">Fs: sound </span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:7pt; color:#142cc8;\">NOTE: Make sure that the upload directories </span></p><p align=\"center\"><span style=\" font-size:7pt; color:#142cc8;\">and storage are selected.</span></p><p align=\"center\"><span style=\" font-size:7pt; color:#142cc8;\">So, how to set the proper sound Fs.</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\"font-family:\'Times New Roman\'; font-size:6pt; font-weight:520; color:#00007f;\">(2500 - 44100) Hz.</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Times New Roman\'; font-size:7pt; font-weight:520; color:#aa5500;\">Nº Trace st(n): </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:6pt; font-weight:550; color:#00007f;\">By Default: st(0) </span></p></body></html>"))


        # Command button actions, function calls
        self.pushButton.clicked.connect(self.cargar)                                        # Call the function to upload file (Load File).
        self.pushButton_2.clicked.connect(self.limpiar)                                     # Calls the function to clean entries (Clean Entries).
        self.pushButton_3.clicked.connect(self.guardar)                                     # Llama a la función para almacenar registros en carpeta (Selección Directorio)
        self.pushButton_4.clicked.connect(self.convertir)                                   # Llama a la función para convertir a Wav (Convertir Archivo)
        self.pushButton_5.clicked.connect(self.escuchar)                                    # Llama a la función para escuchar el sonido Wav (Escuchar Wav)
        self.pushButton_6.clicked.connect(self.Regreso)                                     # Call the function to return to the Home Screen (Back).
        self.pushButton_7.clicked.connect(self.Salida)                                      # Call the function to exit the System (Exit).
        self.pushButton_8.clicked.connect(self.graficar)                                    # Call the function to graph the select records (Plot).

        # Validate so that only decimal numbers are accepted "QIntValidator": For "integers", you must put "QIntValidator".
        self.lineEdit.setValidator(QtGui.QIntValidator())                                   # Only accepts numbers in the Filter Frequency text box.
        # El valor (1,99999) Indica que se van a utilizar solo hasta 5 posiciones de enteros
        self.lineEdit.setValidator(QtGui.QIntValidator(1, 99999))                           # Solo acepta números en la caja de texto de Frecuencia
        self.lineEdit_2.setValidator(QtGui.QIntValidator(1, 999))                           # Solo acepta números en la caja de texto de Número de Traza ts[0] Valor tres digitos

        # Desactivar las cajas de texto inicialmente
        self.lineEdit.setEnabled(False)                                                     # Desactiva la caja de Texto de Fs.
        self.lineEdit_2.setEnabled(False)                                                   # Desactiva la caja de texto de Nº de Traza st[0].
        self.lineEdit_2.setText("0")                                                        # Inicia contenido de caja de texto de Nº de Traza st[0].

        self.pushButton_5.setEnabled(False)                                                 # Disable the Listening button


    """ ------------- Start of Program Functions  ------------ """

    """ Function to open and clean """

    def cargar(self):                                                       # Function, to search and load the records according to the format
        if sistema == "Windows":
            #print("Sistema Windows")

            self.lineEdit_2.setEnabled(True)                                                   # Activa la caja de texto de Nº de Traza st[0].

            self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('NPY Files','*.npy'),
                ('EVT Files','*.evt')))

            self.ruta = Path(self.archivo_abierto)
            self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_4.setFont(font)                  # Printing using text format.
            self.label_4.setText(self.archivo_abierto)  # Printing on the file path label.

        else:

            self.lineEdit_2.setEnabled(True)                                                   # Activa la caja de texto de Nº de Traza st[0].

            self.archivo_abierto=filedialog.askopenfilename(initialdir = "/",
                title = "Please, select file",filetypes = (("All Files","*.*"),
                ('SAC Files","*.sac'),
                ('MSEED Files','*.mseed'),
                ('GSE2 Files','*.gse2'),
                ('WAV Files','*.wav'),
                ('NPY Files','*.npy'),
                ('EVT Files','*.evt')))

            self.ruta = Path(self.archivo_abierto)
            self.ruta2 = self.ruta.joinpath(self.ruta).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_4.setFont(font)                  # Printing using text format.
            self.label_4.setText(self.archivo_abierto)  # Printing on the file path label.

            return self

    def limpiar(self):                                                      # Dejar todo como al inicio

        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Clean all inputs.")
        msg.setText("Are you sure to delete all entries?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                    # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                       # If the answer is OK

            plt.close()                                                         # Close the existing chart.

            # Borra contenido de etiqueta y Cajas de Texto
            self.label_4.setText("")                                            # Borra contenido etiqueta de Ruta de Archivo
            self.label_7.setText("")                                            # Borra contenido etiqueta de Ruta de guardar
            self.lineEdit.setText("")                                           # Borra contenido de caja de texto de Fs.
            self.lineEdit_2.setText("0")                                        # Borra e Inicia el contenido de caja de texto de Nº de Traza st[0].
            # Desactivar la caja de texto inicialmente
            self.lineEdit.setEnabled(False)                                     # Desactiva la caja de Texto de Fs.
            self.lineEdit_2.setEnabled(False)                                                   # Desactiva la caja de texto de Nº de Traza st[0].

            self.pushButton_5.setEnabled(False)                                 # Desactiva el boton de Escuchar

        else:
            pass


    def guardar(self):                                                      # Función para búsqueda de registro de acuerdo al formato
        if sistema == "Windows":
            #print("Sistema Windows")
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_7.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_7.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

            # Activar las cajas de texto inicialmente
            self.lineEdit.setEnabled(True)                                  # Activa la caja de Texto de Fs.
            self.lineEdit_2.setEnabled(True)                                # Activa la caja de texto de Nº de Traza st[0].

        else:                                                               # If the system is Linux
            self.archivo_abierto2=filedialog.askdirectory(initialdir = "/",
              title = "Please, Select Folder")

            self.ruta3 = Path(self.archivo_abierto2)
            self.ruta4 = self.ruta3.joinpath(self.ruta3).resolve()

            font=QtGui.QFont()
            font.setFamily("Times New Roman")
            font.setPointSize(8)
            font.setBold(False)
            font.setItalic(False)
            font.setWeight(60)
            self.label_7.setFont(font)                                      # Impresion mediante el formato de texto
            self.label_7.setText(self.archivo_abierto2 + "/")               # Impresión en la eiqueta de la ruta del fichero

            # Activar las cajas de texto inicialmente
            self.lineEdit.setEnabled(True)                                  # Activa la caja de Texto de Fs.
            self.lineEdit_2.setEnabled(True)                                # Activa la caja de texto de Nº de Traza st[0].

    def graficar(self):                                                     # 1.- Función para graficar el Registro

        try:

            # Verificar que la etiqueta del registro no este vacía
            if not self.label_4.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Record")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            elif not self.lineEdit_2.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Trace")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            else:
                # Load the file
                plt.close()                                                 # Close the existing chart.

                archivoFil1 = (self.label_4.text())                         # Lectura etiqueta del Registro

                st  = obspy.read(archivoFil1)                               # Lectura archivo de acuerdo al formato

                # Ingresar y convertir a entero el valor string de la caja de texto Nº Trazas st[0]
                NTraza = (self.lineEdit_2.text())                           # Lectura del contenido de la caja de texto Nº Traza st[0]
                Ntraza2 = int(NTraza)                                       # Convierte el valor del Nº de Traza a entero
                tr = st[Ntraza2]                                            # Asigna el número de traza indicado al Stream para tratamiento del registro

                tr.stats.station
                tr_filt = tr.copy()
                s = len(tr)

                t = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                plt.plot(t, tr.data, 'k', label='Original Record')          # Where 'k' is the color = black
                plt.legend(prop = {'size': 10}, loc='upper right')          # Para colocar la leyenda a la izquierda

                plt.ylabel('Record - Amplitude', color ="blue")
                plt.xlabel('Time [s]', color ="red")
                plt.suptitle("Record : %s " % tr.stats.starttime, color ="red")
                plt.grid()                                                  # presenta la cuadricula en el grafico
                plt.show()

        except:
                plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File does not exist, is Invalid or the Format is not recognized. Please try again...")
                msgBox.setWindowTitle("Invalid Registration Format")
                returnValue = msgBox.exec()
                pass

    def convertir(self): # 1.- Función para Convertir y Almacenar el Registro en sonido Wav en el directorio.

        try:

            # Verificar que la etiqueta del fichero de registro no este vacía
            if not self.label_4.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Record")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            # Verificar que la etiqueta del directorio de registro no este vacía
            elif not self.label_7.text():
                MensCombo2 = QMessageBox()
                MensCombo2.setIcon(QMessageBox.Warning)
                MensCombo2.setWindowTitle("Empty Directories")
                MensCombo2.setText("Please, enter a valid Value")
                returnValue = MensCombo2.exec()

            # Verificar que la caja de texto de frecuencia no esté vacía.
            elif not self.lineEdit.text():
                MensCombo3 = QMessageBox()
                MensCombo3.setIcon(QMessageBox.Warning)
                MensCombo3.setWindowTitle("Empty Value Frequency")
                MensCombo3.setText("Please, enter a valid Value")
                returnValue = MensCombo3.exec()

            # Verificar que la caja de texto de Número de traza no esté vacía.
            elif not self.lineEdit_2.text():
                MensCombo4 = QMessageBox()
                MensCombo4.setIcon(QMessageBox.Warning)
                MensCombo4.setWindowTitle("Empty Trace No.")
                MensCombo4.setText("Please, enter a valid Value")
                returnValue = MensCombo4.exec()

            else:

                plt.close()                                                 # Close the existing chart.

                archivoFil1 = (self.label_4.text())                         # Lectura etiqueta del Registro
                archivoFil2 = (self.label_7.text())                         # Lectura etiqueta del Directorio

                head, tail = os.path.split(self.archivo_abierto)

                root, extension = os.path.splitext(tail)

                F1 = (root + '.wav')                                        # Asigna a F1, la Captura del nombre del registro y añade la extensión .Wav
                F2 = (archivoFil2 + F1)                                     # Asigna a F2 el directorio mas el nombre anterior donde se almacenará el registro

                st  = obspy.read(archivoFil1)                               # Lectura archivo de acuerdo al formato

                # Ingresar y convertir a entero el valor string de la caja de texto Nº Trazas st[0]
                NTraza = (self.lineEdit_2.text())                           # Lectura del contenido de la caja de texto Nº Traza st[0]
                Ntraza2 = int(NTraza)                                       # Convierte el valor del Nº de Traza a entero
                tr = st[Ntraza2]                                            # Asigna el número de traza indicado al Stream para tratamiento del registro

                tr.stats.station
                tr_filt = tr.copy()
                s = len(tr)

                # Cálculo del vector de tiempo para representar el registro
                t = np.arange(0, tr.stats.npts / tr.stats.sampling_rate, tr.stats.delta)

                frec1 = (self.lineEdit.text())          # Lectura etiqueta de la Frecuencia
                # Convertir a flotante el valor string de la caja de texto
                frec2=int(frec1)                      #  Convierte el valor de Frecuencia a entero

                waves.write(F2, frec2, tr.data.astype(np.int16))            # Escribe mediante la función "wave.write" el fichero a onda de formato .Wav

                self.pushButton_5.setEnabled(True)                          # Activa el boton de Escuchar, si se desea eswcuchar el registro

                MensCombo3 = QMessageBox()                                  # Caja de dialogo que muestra que el fichero .Wav ha sido almacenado con éxito
                MensCombo3.setIcon(QMessageBox.Information)
                MensCombo3.setWindowTitle("Wav record file")
                MensCombo3.setText("Wav file created successfully")
                returnValue = MensCombo3.exec()



        except:                                                             # Si existe algún error, esta excepción, capta y produce la caja de dialogo
                plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File does not exist, is Invalid or the Format is not recognized. Please try again...")
                msgBox.setWindowTitle("Invalid Registration Format")
                returnValue = msgBox.exec()
                pass


    def escuchar(self): # 1.- Función para ejecutar escuchar el sonido Wav del Registro.
                        #  Tener en cuenta que el sonido se reproduce hasta finalizar el fichero.
                        # Tanto mas grande el registro conertido a sonido, más la duración.

        try:

            # Verificar que la etiqueta del registro no este vacía
            if not self.label_4.text():
                MensCombo1 = QMessageBox()
                MensCombo1.setIcon(QMessageBox.Warning)
                MensCombo1.setWindowTitle("Empty Record")
                MensCombo1.setText("Please, enter a valid Value")
                returnValue = MensCombo1.exec()

            else:
                # Carga del fichero
                plt.close()                                                 # Close the existing chart.

                archivoFil1 = (self.label_4.text())                         # Lectura etiqueta del Registro
                archivoFil2 = (self.label_7.text())                         # Lectura etiqueta del Directorio

                head, tail = os.path.split(self.archivo_abierto)

                root, extension = os.path.splitext(tail)

                F1 = (root + '.wav')
                F2 = (archivoFil2 + F1)

                chunk = 1024

                archivo = wave.open(F2,"rb")                                # Read the Wav record

                p = pyaudio.PyAudio()                                       # Se inicializa PyAudio

                # Apertura del Stream
                stream = p.open(format = p.get_format_from_width(archivo.getsampwidth()),
                                channels = archivo.getnchannels(),
                                rate = archivo.getframerate(),
                                output = True)

                data = archivo.readframes(chunk)                            # Lectura de la información

                while data:                                                 # Reproducción del Stream
                    stream.write(data)
                    data = archivo.readframes(chunk)

                stream.stop_stream()                                        # Stop Stream
                stream.close()

                p.terminate()                                               # End PyAudio

        except:
                plt.close()                                                 # Close the existing chart.
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Warning)
                msgBox.setText("The File Does not exist, is Invalid or the Format is not recognized. Please, try again ...")
                msgBox.setWindowTitle("Invalid Record File")
                returnValue = msgBox.exec()
                pass


    def Regreso(self):                                                      # Call function to analysis program (Back)
        if sistema == "Windows":                                            # In case it's Windows
            subprocess.Popen(["python", "Menu.py"])
            app.quit()
        else:                                                               # In case it's Linux
            subprocess.Popen(["python3", "Menu.py"])
            app.quit()

    def Salida(self):                                                       # Function to show exit dialog box
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Question)
        msg.setWindowTitle("Exit Module 4 - Signals to Wav sound")
        msg.setText("Are you sure to exit the Module 4 and System?")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        msg.setDefaultButton(QMessageBox.Ok)                                # By default, the focus is on the OK button
        returnValue = msg.exec()
        if returnValue == QMessageBox.Ok:                                   # If the answer is OK
            app.closeAllWindows()                                           # Close all windows



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    # Developed by: Ligdamis A. Gutiérrez E. PhD.
